### ISSUE TITLE
paper TEI button please

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#10]
paper number TEI button please

**Comment by marcolarosa** [comment]
More information please. What is the markup? Do you have a link to the TEI page describing this markup - if so, please provide that too.

**Comment by sophlew** [comment]
TEI mark up button within workspace for manuscript page number
need to confirm which is correct. button will help with consistency <pb=35-236M> or <pb facs="Bates35-218M.jpg"/>

**Comment by marcolarosa** [comment]
@sophlew Last comment doesn't make sense. Please describe the issue in more detail.

**Comment by marcolarosa** [comment]
Closing this as I don't understand what is required. Reopen if needed.
