### ISSUE TITLE
Personal development setup

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#102]
@Conal-Tuohy Can you please consider setting up prettier auto formatting in your dev environment. I use vscode and have it installed so that it auto formats on save which mitigates having to format files manually. If you can use it in your env, it means we will both produce files formatted the same way.

[https://prettier.io/](https://prettier.io/)

**Comment by Conal-Tuohy** [comment]
do you have configuration options, or just rely on prettier's defaults?

**Comment by marcolarosa** [comment]
I just use the defaults but we can put a prettier config into the root of the repo to adjust things if we need to.
