### ISSUE TITLE
Update sef compilation script to deploy tei-to-html.xsl.sef.json to api

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#103]
Please update the xsl compile script to deploy:

* [ ] `tei-to-html.xsl.sef.json` to `api/src/common/tei-to-html.xsl.sef.json`
* [ ] `tei.css` to `ui/src/assets`

**Comment by Conal-Tuohy** [comment]
moved the XSLT source to the API docker container and added the xslt3 compiler and a bash script so it can be compiled from a shell running in that container:

```bash
docker exec -it $(docker ps | grep nyingarn-workspace_api | cut -d ' ' -f 1) bash
```
```bash
root@api:/srv/api# src/common/compile.sh 
SaxonJS 2.5 from Saxonica 
Node.js version v14.19.0
Compiling stylesheet /srv/api/src/common/tei-to-html.xsl
Stylesheet compilation time: 0.92s
Stylesheet exported to SEF file /srv/api/src/common/tei-to-html.xsl.sef.json
```
I think the `tei.css` file is already moved to its proper location, so I didn't do anything with it.

**Comment by Conal-Tuohy** [comment]
This is in a new branch which I haven't yet issued a PR from, BTW

**Comment by marcolarosa** [comment]
This doesn't need to be copied over to the API container. The API folder is mounted into the worker node container (https://github.com/CoEDL/nyingarn-workspace/blob/master/docker-compose.yml#L85) so you just need to update the compile script to copy the file into the right place on that node.
