### ISSUE TITLE
Change to Meta data - Language description 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#108]
Please make the following changes to the Item Metadata under the Core metadata tab.
Add Content Language and Subject Language, remove Language. Content Language should have the 'AIATSIS standard language code' description and use the AIATSIS data set. Subject Language to use the glottolog data set 

thanks

**Comment by marcolarosa** [comment]
I've updated the profiles (8f08e370dbfe37ac5daf6abfc5c6940072804f80) but I can't give you exactly what you want. Both fields will lookup entities of type Language which will match both Austlang and Glottolog. Unfortunately, there is no way to say content language only looks up entities of type Language in austlang and subject language only matches in glottolog.

**Comment by sophlew** [comment]
That's fine. I think the real need is two separate language entries

**Comment by nthieberger** [comment]
Yes, and the prompt wording can me it clear too, 'The language that is the
subject of the document' / 'The language used in the document (e.g.,
English)'
