### ISSUE TITLE
OCR accuracy - marking words unclear 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#110]
The new OCR functionality marks many words as unclear (see the screenshot) 
![Screen Shot 2022-10-18 at 2 15 15 pm](https://user-images.githubusercontent.com/91518014/196330896-52283b9c-f1db-41d0-b3ec-f7b5e0e59a4a.png)
What's the best way to edit this? 
1. Highlight the text and hit the unclear button to remove the advice? or 2. Delete the TEI mark surrounding the word (current option)? 

It also seems that this new version is bringing up more errors than the previous version - could this be right? 
Compare AnonBeverley-001.jpg (untouched) and AnonBeverley-002.jpg (re-processed)

**Comment by marcolarosa** [comment]
There are two questions here:

1. Removing the unclears. At the moment, the unclear button adds `<unclear></unclear>` around the selected text. It doesn't remove it. We would need to code that and that will need some thought. So, at this stage, the only way to remove the unclear markings is to manually select the tags and delete them. I note that this will get tedious very quickly so maybe the solution is to lower the threshold at which something is marked unclear - ie from 70% to say 50%. But that doesn't make a lot of sense in my opinion. Ideally, we want the user to know that the OCR wasn't sure even though that means more work for them. In the end it will lead to a better quality transcription.

2. Number of errors. I'm 83.4567% certain this is not the case. The standard transcription process wasn't marking up the output as TEI. It was just returning the raw text. So there was no marking up of unclear words which is the case in this new version. The actual process for that part (code) hasn't changed. As to the number of errors in the table extraction version - maybe. I don't know if the models AWS uses for raw transcription and table extraction are the same. Likely not. If not, then it is possible that the table extraction model is not as good as the raw text extraction model. Nothing we can do about that.

**Comment by marcolarosa** [comment]
The new transcription editor has a mode whereby markup can be easily removed by highlighting sections of text and clicking a button. I think this makes the issue more maintainable so closing this issue.
