### ISSUE TITLE
Transcription controls

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#114]
Need 3 buttons in the UI to help the user:
* [x] `<` inserts `&lt;`
* [x] `>` inserts `&gt;`
* [x] `&` inserts `&amp;`
* [ ] `"` inserts `&quot;`
* [ ] `'` inserts `&apos;`

**Comment by Conal-Tuohy** [comment]
I think &quot; and &apos; are probably not needed. They only need to be escaped when they appear inside an attribute value, but there's no good reason for them to appear in attribute values. In text content, they can appear just as " and ' respectively

**Comment by marcolarosa** [comment]
resolved by 852e1870f2be5a5302085da93fd3312f1b19460f
