### ISSUE TITLE
Inconsistent ingest processing

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#115]
From @sophlew 

This page in this item: [https://workspace.nyingarn.net/resource/WakkaIIGangulu/WakkaIIGangulu-076B](https://workspace.nyingarn.net/resource/WakkaIIGangulu/WakkaIIGangulu-076B) seems to be processing the ingest differently to the other imports.

See screenshot lines 6 and 8.

![Screen Shot 2022-10-24 at 11 57 25 am](https://user-images.githubusercontent.com/2639995/197428083-5b34bae6-04f9-40e7-ba8e-dc8336f52f43.png)

* `<s>` is being converted to `<del>`
* `<u>` is being converted to `<ul>`

Are these correct given https://github.com/CoEDL/nyingarn-workspace/issues/94?

**Comment by Conal-Tuohy** [comment]
Digivol `s` (strikethrough) we decided it is correct to convert to `del` (deletion).
Digivol `ul` (underline) is now converted to `<hi rend="underline">`. See https://github.com/CoEDL/nyingarn-workspace/commit/0c7ecae27acd32b2a6dd121c1785e983b892f01f#diff-d3cbff776df3bdccc3a754f303a6ad5d5a78e3340955d60f58068c156677b71fR90
