### ISSUE TITLE
New mark up button linked to schema in workspace 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#118]
Please update Workspace with the following mark-up button and their scheme codes

* [x] `<del>`
The <del> </del>(deletion) element contains a span of text which was deleted in the original text, e.g. by being crossed out.
* [x] `<gap>`
The <gap> element is an empty element which is used to indicate a gap, where some text in the original has not been transcribed, for whatever reason. 
* [x] `<graphic>`
The <graphic> element marks the appearance of a graphic embedded in the text. This could be a formal illustration or merely a doodle.
* [x] `<orgName>`
The <orgName> element contains the name of an organisation including a tribal or national or linguistic group.
e.g.<orgName type="tribeName">Wardandee Bibbulmun</orgName>
* [x] `<persName>`
The <persName> (personal name) element contains a proper noun referring to a person, possibly including one
or more of the person's forenames, surnames, honorifics, added names, etc.
* [x] `<placeName>`
The <placeName> element is used to mark up a place name, e.g.
<persName role="speaker">Boongong</persName> m. Of <placeName>Bwokunbup Hill</placeName>
* [x] `<supplied>`
The <supplied> element signifies text which is not a transcription of the original, but was instead supplied by
the encoder.
For example the original text may have been damaged, or the original author may have inadvertently and
obviously left out a word or punctuation character, e.g.
… in <supplied>a</supplied> certain manner.
* [x] `<unclear>`
The <unclear> element contains text which cannot be transcribed with certainty because it’s illegible in the
source. e.g.
<p>Every marginal note in original mss. must be preserved as so
many old notebooks are in faint pencillings. Kajjilgarra's &amp; after
group's dialects are important as these groups are long extinct. The
Benedictine mission of Bishop salvado extended to &amp; beyond Berkshire
valley &amp; all the natives of those areas became extinct. Thus
their inability to attain civilization <unclear>per saltum</unclear>.
</p>

@Conal-Tuohy please supply schema for line-marking, and song phrase

**Comment by sophlew** [comment]
Order list: underline, strike, delete, unclear, paragraph, line, gap, rule, person name, place name, org name, graphic, supplied.

**Comment by marcolarosa** [comment]
I thought we were changing strikethrough to del?

**Comment by marcolarosa** [comment]
I've also implemented controls to remove markup and greatly cleaned up the code - which makes me feel much better about the long term maintenance and enhancement.

https://github.com/CoEDL/nyingarn-workspace/commit/4bc9003ec17a9e9e700accf20daba20c426cd302

**Comment by Conal-Tuohy** [comment]
> @Conal-Tuohy please supply schema for line-marking, and song phrase

I will add this to the schema document, but just quickly; they will be:

For a rule*:

```xml
<milestone rend="rule"/>
```

* I use the typographical term "rule" to avoid confusion with the `<line>` element used to encode a typographical line of text, the `<lb/>` element used to signal the end of a line of text, and the `<l>` element used to encode a line of verse/poetry/song/chant).

NB the `<line>` element is produced by some ingestion processes, but it's not an element which encoders should use themselves; they should use `<p>` to encode actual paragraphs, `<list>` and `<item>` for lists, etc, so we shouldn't provide a `<line>` button.To encode a line of verse or song, the element `<l>` (for "line") is used. ```

An `<l>` element can appear on its own, just somewhere with a `<p>` of text. But more usually a group of these lines (an entire song, or a verse or a stanza) should be enclosed in an `<lg>` (line group) element. 

Similarly, if desired, a bunch of `<lg>` can themselves be grouped into an `<lg>` (for grouping verses in a song).

```xml
<lg>
   <lg>
      <l>Once a jolly swagman camped by a billabong</l>
      <l>Under the shade of a Coolibah tree</l>
      <l>And he sang as he watched and waited till his billy boiled</l>
      <l>"You'll come a Waltzing Matilda with me"</l>
   </lg>
   <lg>
      <l>Down came a jumbuck to drink at that billabong,</l>
      <l>Up jumped the swagman and grabbed him with glee,</l>
      <l>And he sang as he shoved that jumbuck in his tucker bag,</l>
      <l>"You'll come a-waltzing Matilda, with me."</l>
   </lg>
   <!-- etc -->
</lg>
```

**Comment by sophlew** [comment]
Marco please go ahead with rule. 
@conal my feeling is the song <l> <lg> is too complicated. Let's talk with Nick when he is back please. 
Another markup button need - ident

**Comment by Conal-Tuohy** [comment]
@sophlew can you provide a "song phrase" example or two please, so I can see it in context?

**Comment by sophlew** [comment]
User request for two new markup buttons: italics and indent
