### ISSUE TITLE
Branch to work on wiring up tei file assembly

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#119]
@Conal-Tuohy 

I've create and pushed a branch called `implement-tei-file-assembly` that you can use to develop the TEI assembly code. The key bits for you are in the files `tasks/assemble-tei.js` and `tasks/assemble-tei.spec.js`.

It should be straightforward but yell out if it's not. At the moment, it's not properly wired up to the task processing infra. But it works via tests so you should be able to do what you need. Feel free to adapt as required.

**Comment by marcolarosa** [comment]
The branch https://github.com/CoEDL/nyingarn-workspace/tree/implement-tei-file-assembly

**Comment by Conal-Tuohy** [comment]
thanks!
