### ISSUE TITLE
Table extract - newspaper columns are not recognising

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#122]
Table extract is not recognising newspaper columns 
Workspace example from Susie = Teichelmann_SA_Colonist_001 
<img width="1477" alt="Screen Shot 2022-11-18 at 4 23 22 pm" src="https://user-images.githubusercontent.com/91518014/202626899-b7e24195-2a7d-45e0-bcdc-e0ae3f4e049f.png">

Is this something the user should do manually, using table/cell/row markup? 
If so, can we develop some clear instructions

**Comment by marcolarosa** [comment]
This isn't a table so this isn't a bug. And I don't think it should be marked up as a table either. If the columnar structure is important to mark up I'm sure TEI has something for it. But that means more tags and more complexity so I come back to - is the columnar structure important to markup? Or do we just need the raw text?

But it's definitely not a table.

**Comment by marcolarosa** [comment]
I'm not sure what to do about this. We discussed in Monday's meeting but I'm not clear what the outcome was. If it's not an issue (and I don't think it is) - can we close this ticket?

**Comment by marcolarosa** [comment]
As per chat with @sophlew, this is a question of marking up the structure of the document and in this case we don't care about that because it doesn't have any semantic meaning in our world.

**Comment by Conal-Tuohy** [comment]
Columns can be indicated using the `cb` ("column break") element:

```xml
<cb n="1"/>
<p>This text is in column one</p>
<cb n="2"/>
<p>This text is in column two</p>
<cb n="1"/>
<p>This text is in column one again</p>
```
