### ISSUE TITLE
FtP ingestation with people and places marked up with data 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#123]
The mark up of Place and Person in FromthePage Howitt and Fison links to important 
![Nyingarn hw0024](https://user-images.githubusercontent.com/91518014/203197108-9bb4b0a0-b09a-4cce-9e0d-d2c6534f7ace.png)
information and/or web links. The information is lost (or not discoverable) when ingested into Nyingarn. Attached are screenshots: 1. examples of PLace and Person data in FromthePage 2. how the mark up in currently presented in the Nyignarn workspace

Advice on how to manage, please 
![FtP person data](https://user-images.githubusercontent.com/91518014/203196984-9bde21f2-ceab-4b18-8bec-f43e2b630d9f.png)
![FtP person data2](https://user-images.githubusercontent.com/91518014/203196998-2677d73a-0621-439a-ba0e-a50dfbbe459e.png)
![H F FtP](https://user-images.githubusercontent.com/91518014/203197000-5509d87c-49bc-4d0f-99df-a29aa5464cf7.png)

**Comment by Conal-Tuohy** [comment]
NB the [`rs`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-rs.html) element ("referring string") identifies a kind of name (either a proper name or at least some kind of noun phrase that identifies something). There are several similar elements in TEI, grouped into a class of elements called [`nameLike`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.nameLike.html). The `rs` element is the most general purpose element in the set, in that it can refer to any kind of object, not just a person (as `persName` does) or a place (`placeName`). 

The element is a kind of hyperlink; it has a `ref` attribute whose value is the URL of information elsewhere which provides more information about the entity referred to. 

In the case of the Howitt and Fison documents, these URLs point to elements in the teiHeader which provide information about the people, places, etc, identified by the `rs` elements. e.g. in `hw0024.xml` there's this `rs` element:

```xml
<rs ref="#S94966">A. W. Howitt</rs>
```
... which is a reference to the element which has the `xml:id` attribute `S94966`:
```xml
            <person xml:id="S94966">
              <persName>A. W. Howitt</persName>
                <note type="categorization">
                  Categories:
                    <ab>
                      <ptr ana="#category #leaf #root" target="#C410">People</ptr>
                    </ab>
                </note>
                <note type="article">
                    <p xml:id="OTPS94966P0">http://adb.anu.edu.au/biography/howitt-alfred-william-510</p>
            </note>
            </person>
```

**Comment by sophlew** [comment]
@Conal-Tuohy Please upgrade ingestion as you suggest so `<rs>` will show in Nyingarn as `<persName>` and `<placeName>`. Perhaps the metadata needs to be added into Nyingarn under the metadata - linking & creating people. @marcolarosa I'll put on meeting agenda for Monday

**Comment by Conal-Tuohy** [comment]
PR #125 deals with this. 

NB there are still a few `rs` which don't refer to people or to places; they refer instead to an element which in general doesn't identify what kind of entity is being referred to (in practice it seems they are either language groups or national groups). I have left these as `rs`.

**Comment by sophlew** [comment]
@Conal-Tuohy There a
![Uploading Screen Shot 2022-12-02 at 8.50.34 am.png…]()
re still some references to `<rs>` followed by numbers after Person name or Place name in the new H&F ingests, see screenshot. Is this correct?

**Comment by sophlew** [comment]
The ref=numbers refers to a person in the TEI metadata using a unique identifier. @nthieberger should we keep this? 
I think the user would need to look up the ID number on the H&F website example

**Comment by Conal-Tuohy** [comment]
I thought it was worth keeping those links, even if they're not currently usable.

In the fairly short term, there'll be the possibility for a user to download the full TEI from Nyingarn, and then be able to follow those cross-references using some other software.

At present there's no facility in Nyingarn's workspace to dereference those `ref` attributes and retrieve the `person` or `place` metadata, and it's not on the TODO list as such, but it's possible that at some point Nyingarn's HTML preview could be extended e.g. to replicate the functionality of the H&F website by displaying popup notes when you hover your mouse over those names.
