### ISSUE TITLE
New mark up buttons - feedback from users

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#124]
- [ ] Guide the workspace user on the use of the `<table>` `<row>` `<cell>` buttons. For example, what's the order of use? Do you highlight text and then click on `<table>`? 

- [ ] Can the `<unclear>` mark up be a different colour for ease of editing?

**Comment by marcolarosa** [comment]
The first part of this question I think is a documentation one. If a user wants to mark up something as a table then add a table element. Then select the content of the row. Then select the bits of that as cells.

Re: the unclear. I'm not sure. I did look to see if I could do that but wasn't able to figure it out. My feeling is can't be done.

**Comment by sophlew** [comment]
Table guide
<table>
    <row>
      <cell>English.</cell>
      <cell>Menero</cell>
      <cell>Van Diemen</cell>
      <cell>Land.</cell>
      <cell>Adelaide,</cell>
    </row>
    <row>
</table>

**Comment by marcolarosa** [comment]
Ok. I spent a day trying to figure out how to show `unclear` in a different colour and couldn't figure it out. For now, I'm closing this ticket as we discussed the table thing in the meeting and the unclear question is stalled.
