### ISSUE TITLE
Something is up with NewNorcia38c from Digivol

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#133]
From @nthieberger 

### 1 Describe the problem

The digivol ingestion code doesn't seem to like a NewNorcia38c digivol file. I don't know what's happening other than the task runner gets to `processDigivolTranscription` and then seems to stall. It neither succeeds nor fails. Not sure if it's just really slow or there's some other issue.

### 2. Create the test case in drive

[Issue - digivol upload failure/NewNorcia38c - github #133](https://drive.google.com/drive/folders/1l6MeaviNLX1bVeEDfmY-BgAnlwqJoT9W)

**Comment by marcolarosa** [comment]
@Conal-Tuohy This needs to be looked at. I've just put it into my dev instance and it just seems to get stuck. It doesn't succeed or fail but I can see it in the queue as an unacked job. I have no idea what it's doing.

I've put some debugging into `__processDigivolTranscriptionXMLProcessor` and I can see it get to the SaxonJS.transform command but then nothing. Doesn't seem to complete or fail. I don't know how to debug inside that command.

**Comment by nthieberger** [comment]
This is in the workspace so please don't take it out or reupload it, I have added English to the transcript so it is now improved over the digivol version.

**Comment by Conal-Tuohy** [comment]
fixed in #162
