### ISSUE TITLE
Remove subject field from metadata 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#134]
The subject field in the Workspace metadata (About tab) is no longer needed; please remove
<img width="434" alt="Screenshot 2023-01-09 at 10 59 13 am" src="https://user-images.githubusercontent.com/91518014/211225523-9f3f2612-b874-4186-a759-759b064675cd.png">

**Comment by marcolarosa** [comment]
Done as part of metadata meeting.
