### ISSUE TITLE
Mark resource as done

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#14]
Amy wants the ability to mark a resource as being complete - good TEI  - ready to go to repo.

**Comment by sophlew** [comment]
The number of items created starts to bank up, a way to group finished, underway or by collection would be helpful

**Comment by marcolarosa** [comment]
This needs more explanation. Firstly, are  you referring to resources or items? If you mean items then we should start another ticket for this. If resources, then finished I get. If it's not finished then it's underway. What is group by collection?
