### ISSUE TITLE
Nyingarn information is difficult to see in Dark mode

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#142]
Feedback from workspace users: when the computer is in dark mode, the text can't be seen

**Comment by nthieberger** [comment]
Maybe they can switch from dark mode?

**Comment by marcolarosa** [comment]
I need more information about which text can't be seen. Putting my computer into dark mode everything looks the same to me. White background on everything so all text is visible.

**Comment by sophlew** [comment]
here are the screenshots from Tom's computer in dark mode
<img width="640" alt="dark mode1" src="https://user-images.githubusercontent.com/91518014/224879793-db9aad55-45ef-41a6-a63b-79c66287e87b.png">
<img width="640" alt="darkmode2" src="https://user-images.githubusercontent.com/91518014/224879807-1b9d60b6-1177-4447-8f10-d8d650a9f214.png">

**Comment by marcolarosa** [comment]
This isn't happening for me on macos in either firefox or chrome but I'll put a white background on the app and that should fix the issue for those who do (just that I can't test it).
