### ISSUE TITLE
Unable to save metadata in collection metadata

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#148]
Unable to save free text metadata in Collections Metadata. The example I'm testing is KaytetyeALF95 for Bridey. The first two fields = name and identifier had existing information. When we write into the description field & tick the green button, the information is not saved. 
Error message occurs: Unable to save ROC crate file
<img width="1258" alt="Screenshot 2023-03-14 at 11 20 42 am" src="https://user-images.githubusercontent.com/91518014/224860939-03c4babc-ee29-44ba-9417-278c0c20f2ee.png">

**Comment by marcolarosa** [comment]
hmm - this collection is in the DB but not in the backend storage! That's why it's failing. I will delete it and then recreating it will set it up correctly. 

I have no idea how this could have happened.

**Comment by marcolarosa** [comment]
Fixed - by recreating the collection.
