### ISSUE TITLE
Transkribus document ingested but surface files misnamed

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#150]
The document `L17L27-tei.xml` from Transkribus did not ingest properly. The result in the Nyingarn workspace was that there were 30 files named `L17L27-01.tif.tei.xml`, etc, instead of `L17L27-01.tei.xml`

[transkribus ingestion / L17L27](https://drive.google.com/drive/folders/1loY_yV2Qci0jxhTEIGxFhItVkyG128Hb?usp=share_link)

**Comment by marcolarosa** [comment]
Closing this as pull request merged.

**Comment by Conal-Tuohy** [comment]
> @Conal-Tuohy to contact James to create transkibus instructions for Nyingarn webpage

For the record I wrote to James yesterday but I haven't heard back yet.
