### ISSUE TITLE
Assemble TEI test does not actually check the output of the method

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#155]
@Conal-Tuohy Can we do some basic checks of the document created by the `assembleTeiDocument` method? Jest has a [toMatch](https://jestjs.io/docs/expect#tomatchregexp--string) method that you can use to run a few regex matches across the XML to confirm that it looks ok. What do you think?

**Comment by Conal-Tuohy** [comment]
There are some appropriate tests in [transcription-processing.spec.js](https://github.com/CoEDL/nyingarn-workspace/blob/master/tasks/src/tasks/transcription-processing.spec.js#L1059-L1068) using SaxonJS to e.g. check that the textual content of documents are preserved, despite changes to the markup. 

A useful check would be to compare the fragment files after they are glued back together with the original document from which the fragments were taken in the first place. Their tree structure should be isomorphic if not identical. The sequence of non-whitespace text nodes in each document should also match.

**Comment by Conal-Tuohy** [comment]
done in #197
