### ISSUE TITLE
Manuscript images loaded but not presented

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#161]
I have uploaded some test pages for item MS38. These are resized from large jpgs. 
The Workspace processed and accepted the files without an error message. However, they aren't displaying in the View Item Content tab. The presentation flashes a quick view of the thumbnails all red, but not for long so I can't get a screenshot

**Comment by marcolarosa** [comment]
I've just looked at that item and all the images are loading without issue. Please try reloading the page a few times in case you've ended up with something cached badly.

**Comment by sophlew** [comment]
All fixed, thank you
