### ISSUE TITLE
Adding new items to collections - not working

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#168]
Can't add new items to a collection. 
No items are displayed in the list under the tab 'Associate Collections and Items', so can't be chosen and added to the collection. 
Screenshot shows the collection and no items listed underneath
<img width="1271" alt="Screenshot 2023-04-27 at 12 35 31 pm" src="https://user-images.githubusercontent.com/91518014/234745680-8342d208-691f-4c13-84d8-71aa4ffff9ab.png">

**Comment by marcolarosa** [comment]
resolved by b63288cb5756b3deabbaaab5290aa0e9fc57ce75 and 85d31b6e62f96f21ca3e1049afed10fc5c15d4b9
