### ISSUE TITLE
Request - bulk page convert to TEI

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#169]
Request to enable bulk page conversion to Tei instead of individually navigating page by page and clicking the convert TEI button. 
![Screenshot 2023-05-01 at 11 21 54 am](https://user-images.githubusercontent.com/91518014/235388223-86821632-e162-4637-97e0-bafc23b7aaba.png)
![Screenshot 2023-05-01 at 11 21 26 am](https://user-images.githubusercontent.com/91518014/235388230-aefdf346-7ab3-4e50-a3aa-19708f65e77e.png)

**Comment by Conal-Tuohy** [comment]
Is this plain text transcription a legacy of content that was imported a long time ago? Or is it still possible to get plain text into nyingarn?

**Comment by marcolarosa** [comment]
I expect it's a legacy. I'm working on a conversion tool that can run over the repo and fix all of these pages like the button does.

**Comment by marcolarosa** [comment]
Just to add: when a page is OCR'ed now, the placeholder is created as a surface element with a line element around each line of text.

**Comment by marcolarosa** [comment]
This is done. I ran a process over the backend to check and fix all pages that weren't valid TEI.
