### ISSUE TITLE
Repeated transcription table content not in the TEI view 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#170]
Error found in Brady1988-028. The transcription content was edited and the user added three tables. 
In the second table, the first line of content is repeated (see preview tab view). This repeated content 

"English{ | Brothers Sisters or Friends | Parents and Children | Husband and wife
-- | -- | -- | --" is not showing in the Write tab
![Screenshot 2023-05-01 at 11 43 13 am](https://user-images.githubusercontent.com/91518014/235389179-185b4b5a-0c7a-4655-9031-f595cf2075a5.png)
![Screenshot 2023-05-01 at 11 42 33 am](https://user-images.githubusercontent.com/91518014/235389181-ee70af65-506f-4b63-a5dd-52f1da26fe4e.png)

**Comment by marcolarosa** [comment]
The markup on lines 44 and 45 was wrong. The outer element was `cell` and the inner `row` rather than the other way around. I've fixed it.
