### ISSUE TITLE
Question: How to add an arrow symbol into transcription 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#173]
Some manuscripts used the arrow symbol. Is this important to capture, and if so, how? 
See screenshot example 
![Screenshot 2023-05-02 at 10 01 21 am](https://user-images.githubusercontent.com/91518014/235551983-a22baf0b-27a7-484d-b5e6-d14092108599.png)

**Comment by nthieberger** [comment]
➡

Does that work? It is unicode so should

**Comment by sophlew** [comment]
Yes, thank you. Do we need a mark up button for it?

**Comment by nthieberger** [comment]
I don't want to keep adding markup buttons. We could point users to.
unicode table that gives them access to symbols. On a mac this is under
"Emoji and Symbols"

**Comment by sophlew** [comment]
OK will do
