### ISSUE TITLE
Trouble uploading transcription from Digivol 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#174]
Error message (see below) when trying to upload transcription data from Digivol. I chose to export all the validated tasks, see Digivol screenshot
![Screenshot 2023-05-02 at 12 58 56 pm](https://user-images.githubusercontent.com/91518014/235570555-67e6e5e1-abf7-400c-83a7-953661b54d2e.png)

 <div class="el-table__header-wrapper" style="box-sizing: border-box; border-width: 0px; border-style: solid; border-color: rgb(229, 231, 235); --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; width: 936.797px; flex-shrink: 0; overflow: hidden; color: rgb(96, 98, 102); font-family: ui-sans-serif, system-ui, -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

Updated At | Status | Filename | More Information
-- | -- | -- | --

</div></div></div></div>May 2, 2023, 12:54:37 PM	
Holmer1964_fieldnotes-digivol.csv
[For more information see this link: https://nyingarn.net/support/uploading-digivol-data-into-the-workspace/.](https://nyingarn.net/support/uploading-digivol-data-into-the-workspace/)

    When reporting this problem to us please include the following information in the message (and send us the file that caused the error):

    item: Holmer1964_fieldnotes
    file: Holmer1964_fieldnotes-digivol.csv
    error: The document did not contain any pages whose identifiers started with 'Holmer1964_fieldnotes' and matched the regular expression '^[a-z,A-Z][a-z,A-Z,0-9,_]+-[0-9]+[a-z,A-Z,0-9]+\..*$'.
            
    // Admin information
    name: NoPagesWithSuitableIdentifiers
    code: Q{https://nyingarn.net/ns/errors}no-pages-with-suitable-identifiers
    sourceType: digivol
    xsltLineNumber: 11
    xsltModule: process-digivol-csv-to-page-files.xsl

File uploaded to google drive https://drive.google.com/drive/folders/1ESoxj-z2AZwM5YfKdySevWyVpEePoLls?usp=share_link

**Comment by marcolarosa** [comment]
@Conal-Tuohy Can you please take a look? I've had a quick look in the file and it looks like there are correctly named pages: "Holmer1964_fieldnotes-009B.jpg", "Holmer1964_fieldnotes-017B.jpg".

I wonder if this is related to the recent CSV processing change.

**Comment by sophlew** [comment]
Thanks. I also exported all tasks from DigiVol, not just the validated ones and got the same error message in Nyingarn. @Conal-Tuohy let me know if you need to see that file too

**Comment by sophlew** [comment]
@Conal-Tuohy any update on this? I have a community meeting tomorrow (23/5) 2:30pm that will need to review the files after upload into Nyingarn if possible
