### ISSUE TITLE
Unclear TEI errors - individual pages are marked red without error instructions

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#175]
The user uploaded images to item Holmer_1967 for OCR. There were no error messages upon upload or on the home screen (screenshot 1). But when reviewing the content, most of the pages were highlighted red (screenshot 2) without any error instructions. The red highlight goes away if you click save on each page. Is this a bug?  
![Screenshot 2023-05-03 at 8 58 33 am](https://user-images.githubusercontent.com/91518014/235803461-9d3e3bcb-ba0d-4fff-9113-55995cbd627d.png)
![Screenshot 2023-05-03 at 8 58 44 am](https://user-images.githubusercontent.com/91518014/235803468-a1c18c29-c51e-4c00-a7d1-be8f492acf58.png)
![Screenshot 2023-05-03 at 8 58 53 am](https://user-images.githubusercontent.com/91518014/235803547-740e75df-e8ab-4009-ac5d-f175e7a60da2.png)

**Comment by marcolarosa** [comment]
No that's not a bug. The data was written out to the backend but it wasn't checked. The red in this case is an indication to the user that they need to review the transcriptions and confirm each one is good.

**Comment by sophlew** [comment]
Wouldn't they do that anyway?

**Comment by marcolarosa** [comment]
Yes they should. But it doesn't hurt to have the visual indicator for them until they have.
