### ISSUE TITLE
Unable to search for languages in metadata - in both subject and content language fields

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#176]
User feedback, unable to search for languages under the subject and content language fields. Example from user hw0025 
![Screenshot 2023-05-03 at 10 05 29 am](https://user-images.githubusercontent.com/91518014/235810590-4b62ba95-e5d6-47da-81c2-6ac6169305a6.png). 

![Screenshot 2023-05-03 at 10 06 01 am](https://user-images.githubusercontent.com/91518014/235810583-d28196de-6346-4965-950a-5a26a7df2cfd.png)

**Comment by marcolarosa** [comment]
@!$#@ Sorry. That's in describo. I'll look to fix asap but it will take an up update to apply it. I'll be in touch before I do anything.

**Comment by marcolarosa** [comment]
Bug in describo - fixed by cb37c1582dc9f5c6aa61c5c71185987a050ebe56
