### ISSUE TITLE
Error in tei upload

### ISSUE THREAD

**Issue by nthieberger** [CoEDL/nyingarn-workspace#177]
I can't upload a tei doc, with this error:

When reporting this problem to us please include the following information in the message (and send us the file that caused the error):

    item: kalsakau
    file: kalsakau-tei.xml
    error: The document did not contain any pages whose identifiers started with 'kalsakau' and matched the regular expression '^[a-z,A-Z][a-z,A-Z,0-9,_]+-[0-9]+[a-z,A-Z,0-9]+\..*$'.
            
    // Admin information
    name: NoPagesWithSuitableIdentifiers
    code: Q{https://nyingarn.net/ns/errors}no-pages-with-suitable-identifiers
    sourceType: from-the-page
    xsltLineNumber: 16
    xsltModule: process-tei-to-page-files.xsl

**Comment by marcolarosa** [comment]
@nthieberger please email the file to us so we can check it. 

@Conal-Tuohy related to https://github.com/CoEDL/nyingarn-workspace/issues/174 ?

**Comment by nthieberger** [comment]
here's the file

**Comment by marcolarosa** [comment]
@nthieberger the file didn't make it. Please email directly to @Conal-Tuohy if you haven't already. Thanks.

**Comment by Conal-Tuohy** [comment]
> @nthieberger the file didn't make it. Please email directly to @Conal-Tuohy if you haven't already. Thanks.

it's all good; I have the file

**Comment by marcolarosa** [comment]
Done and working
