### ISSUE TITLE
please reword?

### ISSUE THREAD

**Issue by nthieberger** [CoEDL/nyingarn-workspace#179]
Not clear what his means in admin/items: "If this is a new system, then you first need to import the items and collections on the backend storage into the DB. You can do this with this control. You should only really do this once though nothing will break if you run it again." Can it be reworded?

**Comment by sophlew** [comment]
Where is this message?

**Comment by nthieberger** [comment]
https://workspace.nyingarn.net/admin/items

**Comment by marcolarosa** [comment]
This control is moving to another tab 'operations' but happy to reword as well. Any suggestions?

![Screenshot 2023-05-15 at 9 30 15 am](https://github.com/CoEDL/nyingarn-workspace/assets/2639995/984d56f0-1156-4313-bd9b-400d68fd2c83)

**Comment by nthieberger** [comment]
Sorry, I should know what this means, but I don't get it . What is a 'new
system'? How do I import to backend storage .. ? Is this meant for admins?

**Comment by marcolarosa** [comment]
In the next release it will say:

```
The Nyngarn Workspace stores all of the content (data, metadata and state) in the S3 bucket. 
In order to use the service with the data in the bucket, the service first needs to be configured 
from the data. Whilst you should only do this when the service is first installed, nothing will 
break if you run this operation again. 
```
