### ISSUE TITLE
Digivol Tabular CSV

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#18]
Digivol's tabular CSV is very differently formatted to the raw transcription output. Raw transcription has a single column with the content whereas the table csv is many sequentially named columns.

Need to think about how to handle.

**Comment by marcolarosa** [comment]
This is dependent on #9 - need to investigate textract table extraction and then figure out what to do.

**Comment by sophlew** [comment]
BM1648A72 is a clear table example, currently in the workspace

**Comment by marcolarosa** [comment]
Closing for now - we can revisit if required.
