### ISSUE TITLE
request - please scrape all images from this webpage 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#180]
Hey Marco, as discussed, Please scrap the following collection item from State Library of NSW Thomas Collection. 
https://collection.sl.nsw.gov.au/record/nvg82rp1 is higher level link, MS214 has multiple volumes and parts, each with its own link ... 
MS214 volumes 2, 3, 9, 10, 13, 21, 22, 23, 24 and 25

  Not sure if the first link is useful, otherwise, the ones below are the individual parts. thanks 
https://collection.sl.nsw.gov.au/record/1l4dKy51
https://collection.sl.nsw.gov.au/record/nZNvKVEn
https://collection.sl.nsw.gov.au/record/9NaA7vWY
https://collection.sl.nsw.gov.au/record/9NaA70mY
https://collection.sl.nsw.gov.au/record/1xqZ6kQY
https://collection.sl.nsw.gov.au/record/92eV3x0Y
https://collection.sl.nsw.gov.au/record/93QV3eq1
https://collection.sl.nsw.gov.au/record/9Bv7L2B9

**Comment by marcolarosa** [comment]
Done and loaded into the workspace. 80 items in total.

**Comment by marcolarosa** [comment]
Reopening this as the order of the files is wrong.
