### ISSUE TITLE
XML processor logs about missing package

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#190]
nyingarn-workspace-xml-processor-1   | xproc-z-build.properties not found in classpath
nyingarn-workspace-xml-processor-1   | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
nyingarn-workspace-xml-processor-1   | SLF4J: Defaulting to no-operation (NOP) logger implementation
nyingarn-workspace-xml-processor-1   | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Didn't seem to cause an issue though is there a way to fix this (silence it or install the package)?

**Comment by Conal-Tuohy** [comment]
Good catch! Yes I think the way forward is to install the package. I've dealt with it in another project, already. 

What's going on is that the SLF4J package is a logging API that's a generic facade over a variety a number of specific logging APIs. You write your logs using SLF4J, and it delegates to a logging implementation that you've configured it to use. That way you can switch out one logging implementation for another just by a bit of configuration, and don't have to rewrite the code that actually logs messages. The XProc interpreter used in the "xml" container uses SLF4J, but it doesn't configure a logging provider (that's something I should have done), and in the absence of a configuration SLF4J has a no-op implementation up its sleeve that just ignores your logging messages.

I can install a package and that will give us potentially useful logging for the XProc code as well as silencing that warning message.

**Comment by Conal-Tuohy** [comment]
Done in 7402b55
