### ISSUE TITLE
Download TEI button doesn't necessarily reflect latest changes to TEI pages

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#193]
I spent a while editing the third page of `kalsakau` to deal with an invalidity, and check that when I downloaded the full TEI it was also valid, and I found that the content I saved wasn't (or wasn't _always_) reflected in the file I got back from the 'download TEI' button. At one point I typed "xxx" into the start of page `kalsakau-003` and later removed it, but it's still appearing when I attempt a "download TEI".

**Comment by marcolarosa** [comment]
The file doesn't update if it's less than 30 minutes old. This can be revised if it's a big issue but the reasoning is that big items (like Bates) can take quite a long time to generate and most users aren't working that quickly.
