### ISSUE TITLE
Unable to upload XML file to tus service in dev environment

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#194]
I'm trying to test ingesting an XML file through the web UI but the HTTP connection to `http://localhost:1080/files/` is failing. I see that the URL is specified in my `development-configuration.json` file but there seems to be nothing listening on port `1080`

**Comment by marcolarosa** [comment]
This changed ages ago!

"tusEndpoint": "http://localhost:9000/api/files",
