### ISSUE TITLE
XSLT to extract TEI document content

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#201]
I need a way to:
* [ ] submit the whole tei file and get back just the textual content without any markup at all
* [ ] submit the whole tei file and get back a JSON object conforming to the following structure:

```
[
 { page: {{ page-identifier }}, text: {{ text content of page }} },
]
```

Where page-identifier should be like: Bates34-008 (ie {item-name}-{page-number})

**Comment by Conal-Tuohy** [comment]
So when you say "the whole TEI file" - that'd be 

- [ ] a single TEI file, i.e. already reconstituted from the page files? 
- [ ] or are you talking about submitting the TEI in the form of individual page files?

**Comment by Conal-Tuohy** [comment]
done in PR #203
