### ISSUE TITLE
Map tiles going out of date

### ISSUE THREAD

**Issue by nthieberger** [CoEDL/nyingarn-workspace#212]
maptiles say they are expiring on Oct 31.
<img width="244" alt="Screenshot 2023-10-06 at 18 05 30" src="https://github.com/CoEDL/nyingarn-workspace/assets/611488/8ab223c5-0b27-4b2c-a413-c0d47856e605">

**Comment by marcolarosa** [comment]
Where are you seeing this?

**Comment by marcolarosa** [comment]
This is inside describo and so I'll update it there.

**Comment by marcolarosa** [comment]
Done
