### ISSUE TITLE
language identifier

### ISSUE THREAD

**Issue by nthieberger** [CoEDL/nyingarn-workspace#214]
Soemthing strange happening where the identifier here is given as #e14

https://workspace.nyingarn.net/items/NewNorcia38/metadata?id=LiUyRg==

<img width="873" alt="Screenshot 2023-10-20 at 4 03 56 pm" src="https://github.com/CoEDL/nyingarn-workspace/assets/611488/50f5e26e-3c2b-42d6-bd21-36914527d05a">

**Comment by marcolarosa** [comment]
This was a bug in describo that has been fixed.
