### ISSUE TITLE
No OCR

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#22]
Have uploaded an image of a book page rather than a manuscript (from Amy's collection), no text is visible in the transcription (OCR) box. For example ScienceofMan1908

**Comment by marcolarosa** [comment]
Yeah - this is a problem. AWS has a 5MB file size limit for OCR. That file is 12MB. Not sure how to indicate that to the user.

**Comment by nthieberger** [comment]
Can we just specify that no image can be > 5MB if it is to be OCRed?

**Comment by marcolarosa** [comment]
@sophlew has this item been deleted?

**Comment by sophlew** [comment]
I've added it again
