### ISSUE TITLE
Adding users to a record

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#25]
How do you search for the user via their email? The text box allows you to add the email address but unclear how to search

**Comment by marcolarosa** [comment]
Sorry - what do you mean by 'record'? Do you mean adding users to an item? If so - there is no search. Since we require a person to know the email of the person they're inviting then there's no point having a search. You either know it or you don't.

**Comment by sophlew** [comment]
Ok, then the text needs to be change then. It is confusing " search by user email address", it implies the ability to search for a user before assigning them to an item
<img width="1147" alt="Screen Shot 2022-03-08 at 9 19 41 am" src="https://user-images.githubusercontent.com/91518014/157127552-b88db132-b090-4068-8e88-fa17741151e4.png">

**Comment by marcolarosa** [comment]
Ahh ok. Will fix for next release.
