### ISSUE TITLE
Changes to metadata 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#27]
Minor changes to metadata schema, not urgent
spelling mistake - holding institutions 
change descendant permission to language authority permission 
thanks

**Comment by marcolarosa** [comment]
I've made these changes in the profile but it's important to note that the metadata profile is not correct. I've basically invented a whole bunch of stuff just to show the idea but it's up to @ptsefton to do the modelling exercise as it's his area of expertise. Not mine.

**Comment by marcolarosa** [comment]
Closing this.
