### ISSUE TITLE
TEI import pathways

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#28]
@Conal-Tuohy

We need to be able to ingest TEI files coming from fromthepage, oxgarage, transkribus and others. The ingestion process should create stub files for each resource referenced in the file by walking the page breaks and extracting the content in that section.

The stub files must be named as {item id}-{resource id}.tei.xml.

(The workspace operates in terms of items and resources where `resource` means all files about a manuscript page (the tif version, jpeg, webp, thumbnail, OCR output and tei file).

XSLT's to extract the stub files are fine as we can integrate them into the worker node via JS code to operate on the imported TEI files.

**Comment by Conal-Tuohy** [comment]
Where should the `item-id` and `resource-id` values be drawn from? They are components of the image file names are they not? 

Can they always be extracted from somewhere in the TEI XML itself? Or will the ingestion process have these values available through some other means (a manifest of image file names, for instance) and pass them to the TEI file splitter process as a parameter?

**Comment by marcolarosa** [comment]
There must be pb's inside the TEI file that either reference the image via a facs attribute (or something else) or can be reconstructed from the data.

Here's the ftp example where you might need to look in a couple of places to construct the facs entry in the appropriate form.

```
<pb xml:id="F225" n="1" facs="https://fromthepage.nyingarn.net/image-service/225/full/full/0/native.jpg"/>
            <div xml:id="OTP225">
                <fw type="pageNum">Bates35-125T</fw>
                <p xml:id='OTP225P0'>XI, 1, C &amp; d &amp; e
                </p>


            </div>

```

The ingestion process can pass through item id if required. And in that respect, if the XSLT processor gets that id then it should ignore entries in the TEI file that don't match that item id.

**Comment by marcolarosa** [comment]
Hey @Conal-Tuohy i think this is all done. Can we close off this ticket?
