### ISSUE TITLE
Pdf upload capability 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#3]
Will there be pdf upload capability soon?

**Comment by marcolarosa** [comment]
Same answer as the word upload capability in #5

**Comment by marcolarosa** [comment]
User needs to mark up the document as per the requirements of dealing with word docs as set out in #5. But, they then need to be able to upload the whole pdf, have it broken down into one image per page with each image then being sent through OCR.

**Comment by marcolarosa** [comment]
Closing this as it is captured by #28
