### ISSUE TITLE
Difficulty uploading images files

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#30]
Workspace won't except correctly named image files to the items. Two examples BM164891 and Curr_Gifford-1, my files and Amy's. 
<img width="849" alt="Screen Shot 2022-03-16 at 9 51 30 am" src="https://user-images.githubusercontent.com/91518014/158485489-c4f203fa-32ae-48ad-9778-dce87e468ecf.png">
![thumbnail_image002](https://user-images.githubusercontent.com/91518014/158485585-a279b928-388e-4379-96a5-90b3c0d8721d.png)

**Comment by marcolarosa** [comment]
@sophlew Given that most manuscripts will be more than 9 pages should we enforce the numbering scheme to be zero padded with enough zeros to cover the number of pages

**Comment by marcolarosa** [comment]
Can we close this ticket?

**Comment by sophlew** [comment]
yes
________________________________
From: Marco La Rosa ***@***.***>
Sent: Friday, May 6, 2022 4:10 PM
To: CoEDL/nyingarn-workspace ***@***.***>
Cc: Sophie Lewincamp ***@***.***>; Assign ***@***.***>
Subject: [EXT] Re: [CoEDL/nyingarn-workspace] Difficulty uploading images files (Issue #30)


External email: Please exercise caution

________________________________
Can we close this ticket?
