### ISSUE TITLE
Deal with typographical markup in ingested TEI

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#35]
What to do about encoding typographical data?

There is some value in recording a small amount of typographical data, but we need to filter out cruft, and agree on an encoding practice for the typography that remains. 

# Encoding typographical data

There are multiple practices for encoding the typographical data in TEI-world. 

## Schema customisation
One practice is to customise the TEI schema to add dedicated elements such as `<b>` for bold, `<ul>` for underlining, etc. The most popular such customisation of TEI has been TEI Tite; a schema designed for use by commercial vendors. TEI Tite itself is too narrowly constrained for Nyingarn's purposes (it excludes things which Nyingarn will need), but this approach of adding custom elements could be used by a customised "Nyingarn TEI".

On the upside, the markup can be simple for simple cases, though not much moreso than some other techniques, but on the downside, it imposes additional work at any point where markup has to be converted, either from, or to, standard TEI. 

My recommendation is "probably no".

## Attaching typographical data using attributes
Standard practice is to attach typographical data to portions of the transcript by attaching an attribute to an element which encloses that portion of the text. These attributes can be attached to text which is specifically "highlighted" in the text using a TEI `hi` element, but in principle typographical data can be attached to any transcriptional element, e.g. `head`, `row`, `p`, etc.

### Using `style` attributes
The simplest, but least concise, method is to directly embed CSS markup in the form  of [`style` attributes](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.rendition.html#tei_att.style). e.g. `<hi style="font-weight: bold">some text in bold</hi>`.

On the plus side, it's conceptually simple if you know CSS and it allows for a great deal of flexibility in what you encode. I wouldn't recommend it because I don't think we necessarily want to encourage rich typographical markup anyway, and also because CSS is just another complexity for people to grapple with and make mistakes in.

### Using `rendition` attributes
CSS styles can be recorded within TEI `rendition` elements in the `teiHeader`; each `rendition` can have an `xml:id` attribute by which it can be referenced within the transcript, using a `rendition` attribute to point to those `rendition` elements. e.g. `<hi rendition="#bold #ul">some text in bold and underlined</hi>`. 

At the point where the TEI fragments are reconstituted into a full TEI document, we'd need to insert a standad set of `rendition` elements into the `teiHeader` so that these references are each actually connected to a CSS description.

This would be my second-preferred option, I think. It's conformant to the standard, it allows the typography to be explicitly given in CSS, and it's fairly concise and easy to explain/understand for encoders. The only practical difference to using `rend` attributes instead is that with `rendition` attributes you have to type an extra `#` character at the start of each rendition identifier (this marks the reference as being a reference to an `xml:id` within the same document, rather than to an external file), and that's an opportunity for people to forget to do so.

### Using `rend` attributes
An older and even simpler approach is to attach a `rend` attribute whose values are a space-separated list of locally-defined tokens, typically `bold`, `b`, `i`, `ul`, `underlined`, etc. `<hi rend='b ul'>some text in bold and underlined</hi>`.

Originally these `rend` attribute values were just local conventions which you were supposed to document, but which weren't expected to be broadly interoperable, but in more recent versions of TEI it's become possible to associate each token with a `rendition` element, in a standard way, making them fully machine-processable.

This would be my preferred option, I think. It's conformant to the standard, it allows the typography to be explicitly given in CSS, and it's fairly concise and easy to explain/understand for encoders.

# What typography needs to be retained from the original data sources?

Transkribus's OCR distinguishes bold and underlined text, and it represents those with its own conventions which are not CSS but could be translated to CSS fairly easily. It also makes some bogus assertions such as e.g. `fontSize:0.0`, which I've simply thrown away on ingest.

MS Word has a wide range of typographical properties which we would probably want to winnow down to just a few things like font-weight (bold/regular), font-style (italic/regular), underlined, struck out, maybe colour?

Also a fair amount of Word-sourced typographical data would probably be bogus; e.g. people using Word might e.g. have a Times font as their default font, and Arial Bold for section headings, but we shouldn't take that as accurate. Probably more accurate just to retain inline "direct" (i.e. not using styles) formatting?

Does FromThePage have any typographical features?

Does the Amazon OCR engine produce any typographical metadata?

**Comment by nthieberger** [comment]
FTP provides the following codes:
Currently supported tags:

    <add></add> for text insertions
    <cb></cb> to indicate a break between columns
    <date when="20201209"></date> to indicate a date, with an attribute of when
    <figure></figure> to indicate a figure or illustration in the text
    <footnote></footnote> contains the body of a footnote within the original document. This tag should be placed where the footnote marker appears in the text.
    <gap></gap> for missing text
    <head></head> for headings (similar to using ==wiki heading mark-up==)
    <stamp></stamp> for stamps on envelops
    <table></table> with child attributes of row and cell
    <unclear></unclear> for text that is difficult to read
    <strike></strike> or <s></s> or <hi rend=str></hi> for struck through text
    <sup></sup> or <hi rend=sup></hi> for superscript text
    <u></u> or <hi rend=underline></hi> for underlined text
    <date when="YYYY-MM-DD"></date> for dates.  Dates are in [EDTF format](https://en.wikipedia.org/wiki/ISO_8601#EDTF), which supports uncertainty in historical dating.
    <expan orig="original text">expanded text</expan> for expanding abbreviations, for example: <expan orig="qᵃtorsimes">quatorsiemes</expan>
    <reg orig="original text">regularized text</reg> for regularizing text
    <abbr expan="expanded text">abbreviated text</abbr>
    <lb break="no"/>  a soft break tag.  In non-verbatim exports, combines the end of the line with the beginning of the next when a word is broken across the lines.
    <marginalia></marginalia>  for noting marginalia
    <catchword></catchword> for catchwords
    <footnote marker="*">This is a footnote.</footnote>  For adding footnote material.

**Comment by nthieberger** [comment]
and keep in mind that we also have a language detection script that will apply tags after other processing has been completed. We are yet to test this to see how complex the document will become...

**Comment by Conal-Tuohy** [comment]
I'd like to keep this issue focused on the purely typographical aspects of the markup, and open separate tickets for discussing other kinds of markup relating to things like names, dates, editorial corrections, etc.

So far we have Nick's suggestion of recording the following:

> underline, strikethrough, illegible, heading, maybe handwritten addition

In a meeting just now we decided to hang onto horizontal alignment (e.g. "right", "center") as well (at least for now).

Is there anything else?

**Comment by sophlew** [comment]
[Nyingarn BM Tutorial2.pdf](https://github.com/CoEDL/nyingarn-workspace/files/8801841/Nyingarn.BM.Tutorial2.pdf)
Corrections - I think these are different from additions

**Comment by Conal-Tuohy** [comment]
`text-align; left;` is still being retained on table cells in `SLNSW_FL814-355` when it should have been filtered out

**Comment by marcolarosa** [comment]
Closing for now - this covers a lot of territory and a large chunk of it has been addressed in other tickets.
