### ISSUE TITLE
Guidance for using MSWord with Nyingarn

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#37]
Include instructions for using MSWord to encode documents for Nyingarn, including how to convert the MSWord DOCX file into TEI XML using OxGarage.

**Comment by Conal-Tuohy** [comment]
A sample DOCX document and a TEI XML derivative produced with OxGarage are at https://github.com/CoEDL/nyingarn-workspace/tree/master/tasks/src/test-data/msword_example

**Comment by Conal-Tuohy** [comment]
In general they should use Word as usual, to create paragraphs, headings, tables, lists, etc.

For phrases that need special typographical formatting (underline, strikeout, etc), users should apply that formatting directly, rather than using styles; e.g. by selecting the text concerned and clicking the "underline" button on the formatting toolbar or ribbon or whatever it's called these days.

For page breaks, they should insert the page-break identifiers into the text at the point they occur (which might be in the middle of a paragraph), and format the identifier by applying a _character_ style called "Page". In the sample document the "Page" style is typographically distinct, but the actual typographical formatting associated with that style name is irrelevant (it's the name "Page" that matters). It's helpful to have the style include a background colour so that you can see the page breaks clearly.

Once the file is complete, it should be saved in Word's normal DOCX format, with a name that conforms to the Nyingarn naming requirements. It's probably worth saving the file as e.g. "Blah234-tei.docx" rather than "Blah234", because when OxGarage converts the file to TEI XML, it will produce a file called Blah234-tei.xml which can then be directly uploaded to Nyingarn without renaming.

The Word file can then be converted to TEI using the TEI Consortium's "OxGarage" application: https://oxgarage.tei-c.org/

Using OxGarage:

1. From the initial "Convert trom" menu choose "Documents", then "Microsoft Word (.docx)"
2. From the "Convert to" menu choose "TEI P5 XML Document"
3. Click the "browse..." button and upload your DOCX file
4. Download the TEI XML file
5. Upload to Nyingarn as normal

**Comment by marcolarosa** [comment]
@nthieberger @sophlew 

This ticket describes how to take a word doc and mark it up for processing by oxgarage prior to ingest into the workspace. Make sense?

**Comment by sophlew** [comment]
Hey Conal, I do have an few questions - I'll list them here but maybe we could do a quick zoon session? 
My word docs already have page breaks - are these fine or do I need to check in some way? 
I created a 'page' character in styles - does it need any particular properties?
If headings in the existing document don't seem to make sense or are needed - would you remove them? 
thanks
Sophie

**Comment by Conal-Tuohy** [comment]
> Hey Conal @Conal-Tuohy , I do have an few questions - I'll list them here but maybe we could do a quick zoon session? 

I'm currently without my laptop computer with a webcam, and my headset, so not very well placed for that, but hopefully will have it back tomorrow.

> My word docs already have page breaks - are these fine or do I need to check in some way? 

If your document has "hard" page-breaks markers inserted - like these, I mean
![a MSWord page break](https://www.howtogeek.com/wp-content/uploads/gg/up/sshot4d05c1511597d.jpg?width=1198&trim=1,1&bg-color=000&pad=1,1)
... then I am not sure (because I haven't tested) what my import script will make of them; it's expecting page-identifiers formatted with the 'Page' style, and for each one it will create a `<pb>` element and set its  `xml:id` attribute to the formatted identifier. 

The thing is, Word's "hard" page breaks aren't suitable for our purposes because you can't associate an identifier with them. Hence the need for the 'Page' style, but that then means that Word's own "hard" page-breaks are redundant.

Maybe leave the page-breaks in and see how it goes? I suspect it may stuff up the import, and you'll end up with too many "pages" in Nyingarn; some produced from the Word page breaks, and some from the 'Page'-styled identifiers.
But it's a simple thing to test, and if it turns out that it does stuff it up then it will be obvious, and you can always just delete the Nyingarn resource and go back to Word and remove all those page breaks with a find-and-replace operation, and I can fix the import script so it will ignore those page-breaks in future.

> I created a 'page' character in styles - does it need any particular properties? 

No, it doesn't. It's just the name 'Page' that's significant to the import script. 

I suggest giving it a highlight or background colour or something so that it's visually obvious while you're actually working in MS Word, but none of those typographical properties will be retained into the TEI. For the record, here's the relevant part of the XSLT import script that deals with the 'Page'-highlighted identifier, which at that point OxGarage will have turned into a `<hi rend='span'>` element. 
https://github.com/CoEDL/nyingarn-workspace/blob/master/tasks/src/xslt/normalise-docx-via-oxgarage.xsl#L17-L20

> If headings in the existing document don't seem to make sense or are needed - would you remove them? 

I think this may be something for a separate discussion, to be honest. 

I would need to have a better idea of what the headings were, I think, to comment in detail, but in general my advice in text-encoding is to encode all the text that's present in the source document, whether it "makes sense" or not, and if there's a need to make some kind of "editorial invention", then normally one would do that by _adding some extra markup_ to the text concerned. So if a piece of source text were apparently in error then you could record your editorial judgement by marking it up _as an error_ in the source using the `sic` element. See [Apparent errors](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COEDCOR) in the TEI guidelines for more information. Similarly, if a piece of text is unclear, and you have to make a guess at it, you can mark it up as `unclear`, and if there's a piece of text apparently missing (sometimes people will miss out a short word like "a", but it's clear from the context that they meant to write it), then you can supply the text yourself and mark it up as `supplied`. 

I have a feeling that the OxGarage converter may actually allow you to create `sic` markup from a character style whose name is `sic` (I might be wrong, though; I might be thinking of some other conversion software). If I'm right, you can create TEI elements just by formatting the text with a style whose name matches the element name, e.g. `corr`, `add`, `del`, `supplied`, etc. Maybe give it a try? Format something as `sic` (note it's all lower case) and see how it turns out. If OxGarage's own converter doesn't handle it and convert it to `<sic>some bogus text</sic>` it will at least render it as `<hi rend='sic'>some bogus text</hi>`, and our import pipeline can do the conversion.

But the issue of whether to include all the text is properly a question of editorial practice for the project rather than a purely technical hard-and-fast rule. That's why I think another GitHub issue might be needed; we need to whittle down the list of TEI elements to just the elements we want. Personally I think the `sic` element should be in the list of things we do want (and the matching `corr` (correction) element with which you can mark up an editorial correction), but there are dozens more elements which we may not want to include, and I think there's good reasons for wanting to keep the list as short is it reasonably can be.

**Comment by sophlew** [comment]
Thanks Conal. I'll apply these notes and see how I go. 
I tried to add the document named Bates34-tei.docx into oxygarage as suggested and it wouldn't except it

**Comment by sophlew** [comment]
![Screenshot (151)](https://user-images.githubusercontent.com/91518014/167976926-20d497eb-6076-4d08-92ef-3ccdf9984777.png)
here is the screenshot error

**Comment by Conal-Tuohy** [comment]
I think that means you still have the file `Bates34-tei.docx` open in MS Word. You'll need to save and close it before you upload it to OxGarage.

**Comment by sophlew** [comment]
Conal and I fixed a number of issues found in word when formatting the document, styles etc re comments above. 
I tried to upload to Bates34 unsuccessful, no error code
document before oxygarage attached 
[Bates34-tei.docx](https://github.com/CoEDL/nyingarn-workspace/files/8697887/Bates34-tei.docx)

**Comment by marcolarosa** [comment]
@Conal-Tuohy 

This is the error on the rabbit worker node:

```
 2022-05-17T23:22:34.714Z DEBUG: POST: /items/:identifier/resources/processing-status
nyingarn-workspace-rabbit-worker1-1  | Transformation failure: Error XTDE1490 at process-tei-to-page-files.xsl#53
nyingarn-workspace-rabbit-worker1-1  |     A result document with URI file:///tmp/4a5fc47d-29c3-4e11-9b9b-dea14db8568d/Bates34/Bates34-023.tei.xml has already been created
nyingarn-workspace-rabbit-worker1-1  | Error:
nyingarn-workspace-rabbit-worker1-1  |     at new K (/srv/tasks/node_modules/saxon-js/SaxonJS2N.js:3887:513)
nyingarn-workspace-rabbit-worker1-1  |     at /srv/tasks/node_modules/saxon-js/SaxonJS2N.js:4432:435
nyingarn-workspace-rabbit-worker1-1  |     at L (/srv/tasks/node_modules/saxon-js/SaxonJS2N.js:4135:641)
nyingarn-workspace-rabbit-worker1-1  |     at /srv/tasks/node_modules/saxon-js/SaxonJS2N.js:4158:223
nyingarn-workspace-rabbit-worker1-1  |     at wc.ba.forEachItem (/srv/tasks/node_modules/saxon-js/SaxonJS2N.js:3985:583)
nyingarn-workspace-rabbit-worker1-1  |     at /srv/tasks/node_modules/saxon-js/SaxonJS2N.js:4158:193
nyingarn-workspace-rabbit-worker1-1  |     at /srv/tasks/node_modules/saxon-js/SaxonJS2N.js:4136:33
nyingarn-workspace-rabbit-worker1-1  |     at Array.forEach (<anonymous>) {
nyingarn-workspace-rabbit-worker1-1  |   message: 'A result document with URI file:///tmp/4a5fc47d-29c3-4e11-9b9b-dea14db8568d/Bates34/Bates34-023.tei.xml has already been created',
nyingarn-workspace-rabbit-worker1-1  |   name: 'XError',
nyingarn-workspace-rabbit-worker1-1  |   code: 'XTDE1490',
nyingarn-workspace-rabbit-worker1-1  |   xsltLineNr: '53',
nyingarn-workspace-rabbit-worker1-1  |   xsltModule: 'process-tei-to-page-files.xsl'
nyingarn-workspace-rabbit-worker1-1  | }
nyingarn-workspace-rabbit-worker1-1  | 2022-05-17T23:22:36.548Z ERROR: runTask ERROR: Task in /tmp/4a5fc47d-29c3-4e11-9b9b-dea14db8568d
```

**Comment by Conal-Tuohy** [comment]
Yeah that'll do it! There's a duplicate page identifier (`Bates34-023`) in the original Word file, which comes out of OxGarage wrapped in a TEI `<hi rend="Page">` element:

```xml
<p>
	<hi rend="Page">Bates34-023</hi>a</p>
<p style="text-align: right;">From Early MSS., P. 6</p>
<p>Kiamarda, the song</p>
<p>Wilbee ngy, the name of the song. (Baabur)</p>
<p>
	<hi rend="Page">Bates34-023</hi>
</p>
<p style="text-align: right;">34/23</p>
<p style="text-align: center;">19</p>
```

The XSLT doesn't check that these page identifiers are unique in the document, so when it comes to write out the second one, the XSLT processor itself (Saxon) terminates it for trying to write twice to the same output URI (strictly forbidden in XSLT). I can add a check, and terminate the XSLT with a meaningful and helpful error message.

But shouldn't this error (thrown by Saxon itself) have been logged anyway? It would be good to ensure that Saxon errors are logged before catching this error in the XSLT itself, in case there are other errors in future that aren't caught in the XSLT are "handled" by the XSLT processor itself.

**Comment by marcolarosa** [comment]
![Screen Shot 2022-05-18 at 9 41 30 am](https://user-images.githubusercontent.com/2639995/168929545-da413b3d-f953-45e9-8c3c-8928961f5b9e.png)

It is being logged.

**Comment by marcolarosa** [comment]
@sophlew I'm concerned about how much is required on the part of the user to convert a word doc using oxgarage. What are you thoughts on the process?

**Comment by Conal-Tuohy** [comment]
OK so long as it's logged that's fine. Don't know how I missed that. I'll add a check that produces a better error message.

**Comment by Conal-Tuohy** [comment]
I'll let @sophlew comment about OxGarage but to me it seems pretty easy to use. I watched @sophlew screenshare the other day and it took all of about 10s. I think the more difficult bit is the encoding of page numbers in Word, and the main issue she struggled with was about the distinction between Word's "paragraph", "character", and "linked" styles, which I think we could address by providing a Word "template" file for Nyingarn users. There's a lot of scope to provide support by some automation in Word; e.g. macros in Word could check the syntax and uniqueness of the page identifiers, and a custom menu or toolbar could provide access to the "Page" style and to other Word styles that correspond to TEI elements like `unclear`, `sic`, `name`, etc.

**Comment by sophlew** [comment]
agree

**Comment by sophlew** [comment]
I tried the new document Bates34-tei, error message attached
![Screenshot (168)](https://user-images.githubusercontent.com/91518014/168950818-c8e4ceee-ed97-4688-bb1d-bcbbbbbe661d.png)

**Comment by sophlew** [comment]
Amy has reviewed my instructions with screenshots. They were very much focused on Bates, which is confusing/overly complicated. Manuscripts without <pb=hates-50T> blah blah are much easier to prepare.  I'll remove that content. Her other suggestion, include information about why the process is important and needed and shared this document https://www.howtogeek.com/363203/how-to-find-and-replace-formatting-in-microsoft-word/

**Comment by marcolarosa** [comment]
@sophlew Says this is done. Closing.
