### ISSUE TITLE
TEI import fail

### ISSUE THREAD

**Issue by nthieberger** [CoEDL/nyingarn-workspace#38]
I uploaded 4 images and the FTP TEI transcription (that had page references corrected after our discussion). I uploaded the transcription first and it succeeded. I then upload the four images. It has successfully linked the first of the images (https://workspace.nyingarn.net/resource/mackenzie/mackenzie-432), but the next ones were incorrectly sent to OCR and so do not have the proper TEI text, but have OCR junk (https://workspace.nyingarn.net/resource/mackenzie/mackenzie-434)

**Comment by marcolarosa** [comment]
@Conal-Tuohy 

@nthieberger has encoded the pageNum's in two ways:

 <fw type="pageNum">mackenzie-432</fw> and <fw type="pageNum">mackenzie-433.jpg</fw>

Looks like your code is picking up the first (no extension) but not the second (with extension). Please fix so both are acceptable.

**Comment by nthieberger** [comment]
ok, thanks. fixed and works...

**Comment by nthieberger** [comment]
OK, so now it seems it has not matched the images to the text. It only has the first image  and not 4 as were uploaded , and the first one is repeated for each surface .

**Comment by marcolarosa** [comment]
Did you delete each of the resources first? Then upload the tei file and let it process? Then re-upload the original images?

**Comment by nthieberger** [comment]
I deleted the item, but the images didn't change so why did they need to be
deleted?

**Comment by marcolarosa** [comment]
Closing as this is no longer happening.
