### ISSUE TITLE
Pathway from AWS table extract to TEI

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#41]
We need to work out how to convert a table extract from AWS textract to a TEI blob for insertion into the surface element. This processing task will not happen automatically as it's expensive and only some pages will have tables so it will become a control in the interface where the user can say "run this page through the table extract service".

For now, just implement the table extraction in a standalone file so you can get some data out (or use the demo online) and work on the JSON to TEI pipeline. Example code is at https://github.com/CoEDL/nyingarn-workspace/blob/master/tasks/src/tasks/ocr-processing.js#L104-L114.

Things to keep in mind:
If a page has text and a table, the aws table extract service returns only the table data. That needs to become TEI and then get joined into the TEI stub file that already has the same content as text. DO we just add a table into and get the user to remove the duplicated content" Can we do it automatically?

**Comment by sophlew** [comment]
I have included a few manuscripts in Nyingarn with tables Grey_g_12_c_12-009, Bates1907Nativenamesofplaces-02, ColonialSecretary1904-02, HopeBimbar-01

**Comment by Conal-Tuohy** [comment]
@sophiew could you either attach those documents here or email them to me, please? thanks

**Comment by sophlew** [comment]
These examples are not word transcription documents. The manuscript image only has been uploaded into the Nyingarn workspace

**Comment by Conal-Tuohy** [comment]
Yes please. Ideally just attached to this issue, unless it's confidential.

**Comment by sophlew** [comment]
Github doesn't accept tiff files, I'll email

**Comment by marcolarosa** [comment]
Done

**Comment by marcolarosa** [comment]
317a81cb202dc20c1c2a4292e3f1a5474c8a42ca
