### ISSUE TITLE
Validate that TEI XML files don't contain duplicate page identifiers

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#43]
If a TEI XML file has non-unique page identifiers then the ingestion-processing XSLT currently attempts to output content multiple times to the same output URI and gets slapped down by Saxon. https://github.com/CoEDL/nyingarn-workspace/issues/37#issuecomment-1129413491

The XSLT should check that there are no duplicates among the identifiers of the `surface` elements, and if there duplicates, it should terminate with an error message that details the duplication.

**Comment by Conal-Tuohy** [comment]
@marcolarosa do we also need some way to route these ingestion messages back to a UI where the responsible user can see them? Or is that already done?

**Comment by marcolarosa** [comment]
That [screenshot](https://github.com/CoEDL/nyingarn-workspace/issues/37#issuecomment-1129422784) is from the UI. The user is shown the error message with instructions on what to tell us. The stack trace I put into the other ticket is what's in the worker container logs.

**Comment by Conal-Tuohy** [comment]
Thanks! I'm testing out this new check in a new branch just now, and I'll post a pull request shortly.

**Comment by sophlew** [comment]
I have updated the original docx file for Bates34. The page number wasn't a duplicate; the pages are Bates34-023 and Bates34-023a however the Page style allocation hadn't recognised the full page name for Bates34-023a
I'll double-check for more within the document. Conal, this probably happened when we were doing the mass renaming/styling.

**Comment by sophlew** [comment]
I'll share the revised instructions shortly but next issue related to this: Baets34 has multiple folders with 100 plus page transcriptions see screenshot. I would prefer to prepare each folder of Bates34 containing 1 docx document at a time but this means there will be multiple Bates34-tei.xml documents. Does that make sense? How do we get around this?

**Comment by Conal-Tuohy** [comment]
The ingestion code now checks for duplicate identifiers, and also the duplication in the sample document (an artifact of a find/replace operation in Word) is fixed, so closing this now.
