### ISSUE TITLE
Workspace TEI mark up from oxygarage conversion process

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#50]
We have had success ingesting docx via oxygarage conversion documents into Nyingarn. Hooray, nice work team!
The Example is Bates34. Now looking at the data, I think there is too much markup, for example font size and it makes it very difficult for the viewer to read the actual content, see below. The end of line breaks also seem to be missing, see text runs across the whole screen instead of line by line sequence in the original document. I have also included the original text at the bottom.  

```
<surface xmlns="http://www.tei-c.org/ns/1.0" xml:id="Bates34-177T"><p/>
<p style="text-align: right;"><hi style="font-size:12pt">34/177</hi></p>
<p style="text-align: center;"><hi style="font-size:12pt">40</hi></p>
<p><hi style="font-size:12pt">are its favorite feeding grounds.</hi></p>
<p><hi style="font-size:12pt" xml:space="preserve">In the emu dance of the Bunbury and Busselton natives, the long stately stride of the bird was imitated most wonderfully, the left hand and arm </hi><hi rend="strikethrough" style="font-size:12pt">are is</hi> <hi style="font-size:12pt" xml:space="preserve">{being} raised above the head and slightly crooked to represent the head and neck of the bird. As the performers dance with the high knee action, the arm and </hi><hi rend="strikethrough" style="font-size:12pt">had</hi><hi style="font-size:12pt" xml:space="preserve"> {hand} are moved as the bird moves its head and neck when walking. A second {</hi><hi rend="strikethrough" style="font-size:12pt">???</hi><hi style="font-size:12pt">} act shows the feeding, {</hi> <hi rend="strikethrough" style="font-size:12pt">???</hi><hi style="font-size:12pt">} “love-making”, chasing, and final capture of the bird.</hi></p>
<p><hi style="font-size:12pt">The emu and kangaroo dances were amongst the Bibbuluk ke’ning (Bibbil {</hi>  <hi rend="strikethrough" style="font-size:12pt">???</hi><hi style="font-size:12pt">} people’s dances), and were performed at the Vasse, Augusta, Bunbury, Murray and Swan districts, and probably further north and east.</hi></p>
<p><hi style="font-size:12pt">All the larger animal and bird dances dealt with the chasing and killing of the animal represented, as well as with their habits etc. In the kangaroo dance the performers stood in a semicircle while two of their number; representing the kangaroo and the hunter-detached themselves from the group, and while one assumed the attitude of the animal when feeding, rising at intervals to gaze about for possible enemies, standing absolutely motionless in the exact attitude the kangaroo adopts, and then {</hi><hi rend="strikethrough" style="font-size:12pt">???</hi><hi style="font-size:12pt">} stooping down to graze, the other native-the hunter-creeps cautiously towards his quarry against the wind, changing his position as the animal turns hither and thither while feeding. He moves backwards or forwards, throws himself on the ground, and acts in every detail as though he was chasing the real animal. Eventually he closes in upon it, lifts his spear and sends it hurling close beside the animal which immediately falls.</hi></p>
<p><hi style="font-size:12pt">During the performance the remaining members stand perfectly still, watching the game intently. When the scene is ended, two more take the place of kangaroo and hunter, and the game proceeds. As no two natives hunt alike, the methods of each are noted by spectators and performers, in order that some fresh hint may be taken in the mode of kangaroo “stalking” called {“yon’gar} ngardongin” by the Southwestern people.)</hi></p>
<p><hi style="font-size:12pt">Moonlight nights are generally chosen for this kind of pastime, but the central fire also casts its light upon the players. There may or may not be musicians and singers for these displays, but the songs are not allusive, and the music is merely played for the rhythm and measure of the movements.</hi></p>
<p><hi style="font-size:12pt">In the Eucla district a local dance was performed by both men and {</hi><hi rend="strikethrough" style="font-size:12pt">wom</hi><hi style="font-size:12pt">}</hi></p>
</surface>
```

```
<pb=34-177T>
34/177
40
are its favorite feeding grounds.
In the emu dance of the Bunbury and Busselton natives, the long stately stride of the bird was imitated most wonderfully, the left hand and arm are is {being} raised above the head and slightly crooked to represent the head and neck of the bird. As the performers dance with the high knee action, the arm and had {hand} are moved as the bird moves its head and neck when walking. A second {???} act shows the feeding, {???} “love-making”, chasing, and final capture of the bird.
The emu and kangaroo dances were amongst the Bibbuluk ke’ning (Bibbil {???} people’s dances), and were performed at the Vasse, Augusta, Bunbury, Murray and Swan districts, and probably further north and east.
All the larger animal and bird dances dealt with the chasing and killing of the animal represented, as well as with their habits etc. In the kangaroo dance the performers stood in a semicircle while two of their number; representing the kangaroo and the hunter-detached themselves from the group, and while one assumed the attitude of the animal when feeding, rising at intervals to gaze about for possible enemies, standing absolutely motionless in the exact attitude the kangaroo adopts, and then {???} stooping down to graze, the other native-the hunter-creeps cautiously towards his quarry against the wind, changing his position as the animal turns hither and thither while feeding. He moves backwards or forwards, throws himself on the ground, and acts in every detail as though he was chasing the real animal. Eventually he closes in upon it, lifts his spear and sends it hurling close beside the animal which immediately falls.
During the performance the remaining members stand perfectly still, watching the game intently. When the scene is ended, two more take the place of kangaroo and hunter, and the game proceeds. As no two natives hunt alike, the methods of each are noted by spectators and performers, in order that some fresh hint may be taken in the mode of kangaroo “stalking” called {“yon’gar} ngardongin” by the Southwestern people.)
Moonlight nights are generally chosen for this kind of pastime, but the central fire also casts its light upon the players. There may or may not be musicians and singers for these displays, but the songs are not allusive, and the music is merely played for the rhythm and measure of the movements.
In the Eucla district a local dance was performed by both men and {wom}
```

**Comment by sophlew** [comment]
@Conal-Tuohy Morning Conal, have you seen this issue? I'm putting Bates 34 back into the workspace so you can see

**Comment by Conal-Tuohy** [comment]
Hi @sophiew!
I'd like to close this issue and split into two issues because I think the "excess markup" and "ultra-wide lines" are quite distinct problems with distinct solutions. 

Regarding the excessive markup relating to typography: can I point you to the existing issue #35 where I raised a question about what typographical markup needs to be retained? Let's carry on the discussion there.

In particular we need to collate a list of typographical distinctions which we DO want to keep, so I can throw out everything else.

The ultra-wide lines is I believe a problem with the presentation layer (i.e. the formatting of the web page in which the TEI is displayed).

**Comment by Conal-Tuohy** [comment]
Closing this now and redirecting to issues #35 re typographical markup, and #57 for line-wrapping

**Comment by sophlew** [comment]
Reopening this ticket. Tested Bates34 today in the workspace. This is an existing word transcription, modified as per our instructions and passed through oxgarage. Result in the workspace still has 'junk' markup around the transcription text e.g font size, body text, see screenshot
![Screenshot (249)](https://user-images.githubusercontent.com/91518014/177686562-a04a8609-3f9b-484e-bd91-b8f5ffd959bf.png)

**Comment by sophlew** [comment]
Examples from today. A lot of surrounding code still present 
![Screenshot (257)](https://user-images.githubusercontent.com/91518014/177900056-1f4a7c55-3a87-4176-979e-e83b68a98500.png)
![Screenshot (258)](https://user-images.githubusercontent.com/91518014/177900060-0c828e45-8737-42ee-bf81-598c55ccc98a.png)

**Comment by Conal-Tuohy** [comment]
I downloaded Bates34-tei.xml from https://drive.google.com/drive/folders/1Iltr2bt3HPIiW9aNDD5DK7AEx_4ZMEqU but it seems to be a different version than the one in the screenshot. There are `<seg>` elements in the screenshot which have attributes containing unwanted typographical information, but my version of the file contains no `<seg>` elements. It would be helpful to have the actual data available so I could run tests to see why and how the typographical stuff is making it through. Looking at the code for purging this stuff it does seem to me like font-size etc should be purged, even if it's attached to a `<seg>` element, so it's definitely a bug.

**Comment by Conal-Tuohy** [comment]
The "text-align: justify" I would expect to make it through the formatting filter; text-alignment is something we decided to keep (except if it has the value "left" because that's a default). But perhaps we should ditch "text-align: justify" as well, and retain only "text-align: right" and "text-align: center"?

**Comment by Conal-Tuohy** [comment]
There are `rend` attributes with various values which should have been purged. Looking at the code I would expect it to have removed them, so I'm going to need to debug this.

**Comment by sophlew** [comment]
https://docs.google.com/document/d/18Bz0W9Bl_RcScOnMLiuBWKdInsd7Fr9A/edit?usp=sharing&ouid=101877557955064153336&rtpof=true&sd=true

**Comment by sophlew** [comment]
Tracking of excessive tei markup documents - docx and tei-xml here
https://drive.google.com/drive/folders/1hRFzgsWmpZ3aBdOsJDPwQiSpfG8UVxln?usp=sharing

**Comment by marcolarosa** [comment]
Closing this ticket and starting a new one given new system of reporting. Replaced by https://github.com/CoEDL/nyingarn-workspace/issues/73
