### ISSUE TITLE
Brainstorm Workspace markup button

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#52]
We currently have the following markup buttons to the right of the transcription in the workspace: Date; Underline; Strikethrough; Unclear; Line Break; Language; Person. 
Creating this ticket so we can brainstorm and discuss others we might need & their purpose. 

Ideas: Symbols; Place;

What will the mark up look like in the transcription box? The more simple the better. If complicated too, it makes reading the transcription text difficult

**Comment by Conal-Tuohy** [comment]
Most of these have standard TEI elements:
```xml
<date>
<del>
<unclear>
<lb>
<lang>
<persName>
<placeName>
```
There's a `<ul>` (underline) element defined in the customisaton of TEI known as "TEI Tite", which I think we should use. TEI Tite also defines several other similar elements: https://tei-c.org/release/doc/tei-p5-exemplars/html/tei_tite.doc.html#phrase of which I think `<sub>` and `<sup>` for superscript and subscript might be useful?

Whereas with the `<unclear.` element you enclose your best guess as to what the unclear text is, if it's totally unreadable or missing (e.g. page tear, ink blot, etc) then `<gap>` can be used to indicate the missing word. 

Perhaps also including `<supplied>` for when a word is missing from the text but the omission is obvious and you (the transcriber/editor) supply the missing word. So e.g. a text that says "I was no doubt that ..." you could mark that up as:

```xml
I was <supplied>in</supplied> no doubt that ...
```

Relatedly there's `<sic>` used to mark up apparent errors in the original text, and `<corr>` to provide a correction. A `<sic>` and a `<corr>` are often grouped together in a `<choice>` element (to indicate that the original error and the correction are two alternative ways you can choose to read the same bit of text), though the use of `<choice>` is optional and could be inferred if the `<sic>` and `<corr>` are adjacent in the text anyway.

```xml
<sic>Victria</sic><corr>Victoria</corr>
or
<choice><sic>Victria</sic><corr>Victoria</corr></choice>
```

What's the story with your comment about "symbols" @sophiew? Is this about adding markup to provide a textual description of a non-standard symbol? e.g. "a funny-looking squiggle like a figure 8 with a vertical line through it"?  Or a way to pop up a list of standard symbols (a virtual keyboard) that the user can scroll through? Or both?

**Comment by Conal-Tuohy** [comment]
NB with the `<date>` element, you can supply an unambiguous date, e.g. if the text says "July" but you know it's 1890, you can encode that as:
```xml
<date when="1890-07">July</date>
```
That's a case where the button UI could usefully pop up a small HTML form for a user to enter a date or choose it from a calendar widget.

**Comment by sophlew** [comment]
For symbols âôûὸόàēā

**Comment by Conal-Tuohy** [comment]
@sophlew:
> For symbols âôûὸόàēā

OK! If it's just applying diacritic marks like circumflexes, macrons, acute and grave accents, then we could have one toolbar button per diacritic, and you could select the letter in the text which you wanted to accent, and click the button to add the diacritic mark to it. Maybe a single "diactrics" button that pops up a list of possible diacritics to select from?

But if there's a need for a range of symbols I think we'd need a larger popup virtual keyboard. Have you also had a need for less commonly used punctuation like « and », or other non-alphabetic symbols like §, ½, º, †, ‡, arrows, stars, or geometric shapes like triangles, squares and circles, maybe even Greek letters like α, β, γ, etc. (sometimes used for numbering lists)?

**Comment by sophlew** [comment]
I would say just diacritic marks like circumflexes, macrons, acute and grave accents but Nick will know better and I'll check with Amy too
