### ISSUE TITLE
Workspace linking users to items - unsure if this is working 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#56]
I'm adding Amy (user) to all her items from the admin workspace items view. 
I add her email address, and click attach user. It looks like it has worked however in the list above (see screenshot), Amy's details are not listed 
![Screenshot (173)](https://user-images.githubusercontent.com/91518014/171063525-c9de9492-b4ac-41ef-930b-6b447fb93e87.png)

**Comment by marcolarosa** [comment]
Fixed by https://github.com/CoEDL/nyingarn-workspace/commit/28bc36cb73b44498c6d2e7a11f1e217f43bbd716 and https://github.com/CoEDL/nyingarn-workspace/commit/3508d50f990e38dbf8e0b7a276552111e2af6b93

Updating prod soon
