### ISSUE TITLE
Transcription text box needs line-wrap

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#57]
Originally raised in issue #50

Some data sources (e.g. transcriptions done using Word and converted to TEI with OxGarage) produce long paragraphs without linebreaks, and the result is too wide for the transcription text box in the Nyingarn UI.

I think this just a CSS issue.

**Comment by marcolarosa** [comment]
Here's two examples of linewrapping in the code editor. @sophlew made the not unreasonable comment `??? line wrapping needs to look exactly like the manuscript page`. At this level it's not possible. That means the ingest process needs to add line feeds / carriage return after </lb> markers in the text.

![Screen Shot 2022-05-31 at 1 23 32 pm](https://user-images.githubusercontent.com/2639995/171087486-ec021955-98c4-4f95-8823-1a76b89ef645.png)
![Screen Shot 2022-05-31 at 1 22 07 pm](https://user-images.githubusercontent.com/2639995/171087500-b0968048-7af6-4568-a866-7bdbb75b9116.png)
:

**Comment by marcolarosa** [comment]
@Conal-Tuohy what do you think?

**Comment by Conal-Tuohy** [comment]
I don't think I've thrown away any newline characters in the ingest process, so when a document is ingested into Nyingarn I'd have thought that the line endings should look the same as in the document's previous life in FromThePage, Transkribus, or wherever. If the line endings are munted that's a definite bug and I'd appreciate a bug report.

MSWord is perhaps a different story though; in Word a paragraph of text is just a sequence of characters; Word just wraps lines at the edge of each column, and as far as I know I don't think Word saves information about line endings in the DOCX file (it's possible, I guess; I haven't checked). In any case, even if it does, such information is lost in the conversion to TEI via OxGarage.  I think for transcribers using Word, if line endings are significant they should enter a paragraph mark (by pressing ENTER) or a line break (by typing SHIFT+ENTER), and those should persist into the TEI (again, if they don't, then that's a bug, because I've aimed to preserve them).

For some of the data sources I've added explicit TEI `<lb/>` (line break) markup, but I'm not sure if I've done that for all of them.

**Comment by Conal-Tuohy** [comment]
I think the line-wrapping looks good in the screenshots, for what that's worth.

It's be worth enabling CodeMirror's "xml mode" while you're at it, I reckon.

**Comment by sophlew** [comment]
The line wrapping is not correct in this manuscript example SLNSW_FL814-473. Some words are moved onto the next line before the </p> code. This is because of the transcription window size? 
see lines <p>Struggle		Suck - as wound &amp;c Morè-bon</p> and
<p>Subscribe - write	Ber kerk	Sulky Nar-rite (Wav)</p>
![Screenshot (231)](https://user-images.githubusercontent.com/91518014/174525756-ab79c455-2e2c-4753-9e26-02cbe70e8b6c.png)

**Comment by Conal-Tuohy** [comment]
It looks to me like the line of text is too wide to fit in the narrow transcription editor, so it's wrapped around. 
Moving the toolbar buttons from the right hand side of the editor to the top might be enough to fix the issue?
