### ISSUE TITLE
Reorganise error-handling

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#59]
- [x] Set up an error-handling subsystem with a table of errors with unique codes. When errors are thrown, pass them to this subsystem for logging and for routing back to the UI to show the appropriate user(s).

What to include in the central error table?

- [x] The error code (NB error codes thrown from XSLT will have two parts: a namespace URI, and a "local" code which is an arbitrary string)
- [x] An error message, maybe even a template string? If an error included a map of name/value pairs, they could be expanded into a template. e.g. `Error while processing {identifier}. The page number {page} didn't match the expected pattern {pattern}.`
- [x] A URL that could provide more detailed information (e.g. a wiki page)
- [ ] ~~Some kind of "severity" level? (e.g. debug, info, warning, error)~~

- [x] Revise error-throwing code (including XSLT) so that it throws the appropriate errors, including any embedded parameters to be expanded in a message template.

**Comment by sophlew** [comment]
That sounds good Conal. I'm attaching a screenshot of clear instructions I thought were great
![Screenshot (186)](https://user-images.githubusercontent.com/91518014/171518952-e98c02c4-b129-43b1-b4e1-2baa4745761e.png)

**Comment by Conal-Tuohy** [comment]
> A URL that could provide more detailed information (e.g. a wiki page)

@sophlew is going to add some URLs of WordPress pages to the ticket https://github.com/CoEDL/nyingarn-workspace/issues/91 which will be relevant to these errors, and @Conal-Tuohy will then attach those URLs to the `error-definitions.json` file, and @marcolarosa will ensure they get surfaced appropriately to the end users.

**Comment by marcolarosa** [comment]
> > Some kind of "severity" level? (e.g. debug, info, warning, error)
> 
> @marcolarosa do you think there's value in having some kind of "severity" level attached to the error definitions? I added that action item just because I know lots of error-handling and logging systems do have error codes.
> 
> I think all the errors thrown from the XSLT are genuinely fatal errors, but maybe there'd be value in having a `severity` property for errors from other sources? If there's no immediate need then I reckon we should park it and add it only if and when it turns up as a real requirement. Or I could just add `"severity": "error"` to every one of the errors in the `error-definitions.json` file.

I'm not sure we need it. I think you are right that from the XSLT layer the errors are fatal. In the JS layer, these errors are not logged in the DB so a severity doesn't make sense for that layer anyway. They just get surfaced to a user so they know what to do next.

**Comment by Conal-Tuohy** [comment]
Whoops I closed this a little prematurely. Actually there's still the last little step of surfacing any `url` property of these errors to the end user which is over to you, @marcolarosa
