### ISSUE TITLE
Error processing tei file from oxgarage

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#60]
@sophlew reported an issue with c018660.

The page markers in the document are:
```
<hi rend="Page">c018660-004h.jpg</hi>
```

but the code is producing files named `c018660-004h.jpg.tei.xml` - note the `jpg` extension in the name.

**Comment by marcolarosa** [comment]
Yes - I said that. The code should be removing any extensions found in the identifier.

**Comment by sophlew** [comment]
I can simply remove it because this is a test case. 
State Library NSW collection numbering is odd and has changed over time. I'm working with the team Stephen, Andrew & Corey to work out the best way.  See below, two names for the same manuscript page. I think we will probably go with SLNSW numbering but was testing the scenarios.
c018660004h.jpg = SLNSW_FL814347.jpg
c018660006h.jpg = SLNSW_FL814351.jpg

**Comment by marcolarosa** [comment]
It doesn't matter. We need to be able to handle page markers with and without extensions because it's not unreasonable to expect that a user would do that. For now, please leave so @Conal-Tuohy has an example to test from and then you can change if you want.

**Comment by sophlew** [comment]
OK 
The issue arising from this test also, the workspace accepted the tei-xml , no error message but took a long time to load. So I knew there was something wrong but workspace didn't communicate to the user

**Comment by marcolarosa** [comment]
I think the initial load work fine. At least it did for me. It is a big document so if it takes a while to process that's not a surprise. The issue is that the page stubs created from it are named incorrectly so the workspace can't find them.

**Comment by Conal-Tuohy** [comment]
@sophlew I have grabbed the file with the problem and added it as a test case in our automated test suite. I've fixed the issue so that file extensions like `.jpg` will be ignored, and @marcolarosa is planning to deploy that fix (along with other updates) on Monday.

So if you want to ingest the file again, after that's deployed, you should find it will work. I'm closing this issue now but feel free to reopen it if it turns out the problem persists.

**Comment by sophlew** [comment]
I have uploaded the c018660-tei.xml file again and it was accepted by the workspace. It takes a very long time but the file is huge. The TEI box is ticked but can't see the transcription yet
![Screenshot (207)](https://user-images.githubusercontent.com/91518014/172280274-9b2820b9-e3a4-4fd7-80de-791782cccd14.png)

**Comment by Conal-Tuohy** [comment]
Reopening this as there clearly still is a problem. I wonder, though, if my fix just hadn't been deployed at the time this document was re-ingested? @marcolarosa ?

**Comment by marcolarosa** [comment]
@Conal-Tuohy yep - I only just updated in the last 30 mins. @sophlew can you please test again?

**Comment by sophlew** [comment]
New upload just now, the same result. TEI ticked but no nothing in the transcription window

**Comment by sophlew** [comment]
Tried this again, see google drive c018660 15 June. The tei.xml file was accepted, tei box ticked but no transcription seen in the transcription box

**Comment by Conal-Tuohy** [comment]
Test document here: https://drive.google.com/drive/folders/1JjuVW65L89ujA5W2diAZRSDdPlu-jFvi?usp=sharing

**Comment by Conal-Tuohy** [comment]
I see there are two documents there in that folder, @sophlew ; what's the difference between the two?

**Comment by sophlew** [comment]
Documents should be the same, they were tested on two different days

**Comment by Conal-Tuohy** [comment]
A fix is ready now to be merged and deployed

**Comment by marcolarosa** [comment]
i'll build and deploy a release with both pull requests first thing tomorrow morning.

**Comment by sophlew** [comment]
The font tei markup has gone from oxgarage conversion documents tested today. See SLNSW_FL814 in workspace. 
Only <p> </p> remaining. This is difficult to example ingested from Digivol, which have <lb/>, See NewNorcia. Is this an item for the user?

**Comment by Conal-Tuohy** [comment]
@sophlew 

> The font tei markup has gone from oxgarage conversion documents tested today. See SLNSW_FL814 in workspace. Only `<p> </p>` remaining. This is difficult to example ingested from Digivol, which have `<lb/>`, See NewNorcia. Is this an issue for the user?

This is off topic for this issue. Could you open a new one please?

**Comment by marcolarosa** [comment]
Fairly certain this is done. Can start a new ticket if we see it again.
