### ISSUE TITLE
Option to upload manuscript images and not to OCR

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#63]
I've been working with Andrew Tanner. He & Stephen have manuscripts in cursive, difficult to read writing. Andrew would like to do the transcription work in Nyingarn without uploading and having to delete the bad OCR.

**Comment by sophlew** [comment]
Alternate option: update images see OCR and chose not to accept it

**Comment by marcolarosa** [comment]
Add a control to the UI to easily wipe the transcription in order to start from scratch.
