### ISSUE TITLE
Tidy up table markup in TEI files from oxgarage

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#68]
Tested the SLNSW example @Conal-Tuohy I showed you yesterday with tables. The result in the workspace delivers lots of code around the transcription that is difficult for the user. You have the word document ready. I only tested one page, see SLNSW_FL814-355 and the screenshot. 
Can we discuss @nthieberger @marcolarosa different view options for the user.
1. with code and 2. without code and allow the user to switch between and/or 
2. presenting the transcription text and code as different colours in the transcription box 
![Screenshot (246)](https://user-images.githubusercontent.com/91518014/177681124-08b82228-6d73-4e2f-9ef6-862061b751f0.png)

**Comment by Conal-Tuohy** [comment]
I think we need to have different github issues for what I think are three different tasks:

1. change ingestion of `<table>` markup to format it on multiple lines, with indentation etc, to improve readability (existing issue #35 I think covers the issue with the crufty `text-align:left` which should have been removed already).
2. enable syntax highlighting for the transcription text box (this is just a feature of codemirror which we aren't using), including providing codemirror with a schema for autocompletion
3. changes to the layout of the various views (facsimile, text+markup, and formatted HTML) on the workspace page, including potentially moving the toolbar from the side to the top, allowing the user to show or hide each view, etc.

These issues are all related in the sense that they all have an impact of the user experience of working with tables, but they're all independent tasks and affecting different parts of the codebase.

Let's keep this issue for the first of these, and I'll open two more.

**Comment by Conal-Tuohy** [comment]
Created new issues to track the other tasks originally raised in this issue:

- #69
- #70
- #71

**Comment by Conal-Tuohy** [comment]
Change `normalise-docx-via-oxgarage.xsl` to add new lines around `table` and `row` elements:
```xslt
    <!-- insert newline characters before each block element for improved readability -->
    <xsl:template match="div | head | p | item | label | note | table | row" mode="docx-via-oxgarage">
```

**Comment by marcolarosa** [comment]
Closing ticket as it seems to have been superseeded by other tickets.
