### ISSUE TITLE
Configure codemirror for maximum TEI-helpfulness

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#69]
- enable syntax highlighting for the transcription text box (this is just a feature of codemirror which we aren't using), 
- provide codemirror with a schema for autocompletion

**Comment by Conal-Tuohy** [comment]
There's an article about using CodeMirror for TEI here:
https://orazionelson.github.io/CodeMirrorXML4TEI/
I don't think we necessarily want to do everything they've done (folding, in particular, I think could just be confusing and wouldn't offer much value since the individual `surface` pages are so small there's no real call for folding anything away).

**Comment by marcolarosa** [comment]
https://github.com/CoEDL/nyingarn-workspace/commit/4ae100bdfbc960e9a85ea505def456a6a09a1fac
