### ISSUE TITLE
Metadata - year of creation 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#7]
Clarification on 'year of creation' field, is this the year the item in the workspace was created? 
Description needed next to field

**Comment by nthieberger** [comment]
Year manuscript created (we will use this to create a time map so it is the date of the earliest appearance of the manuscript)

**Comment by sophlew** [comment]
We also have publication year

**Comment by nthieberger** [comment]
Yes, but not all manuscripts have a publication year

**Comment by marcolarosa** [comment]
I'm closing this ticket because it's not something I can fix. It's part of a broader exercise involving @ptsefton to do the modelling from the sheet to schema.org. I will then implement whatever is defined in that.
