### ISSUE TITLE
add live "HTML presentation" view

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#70]
add an "HTML presentation" view where the XML markup is converted to HTML for meaningful display, run in the browser so it's a "live" display of the XML being edited

**Comment by marcolarosa** [comment]
The XSLT required for this was first discussed in https://github.com/CoEDL/nyingarn-workspace/issues/29 and then referenced in https://github.com/CoEDL/nyingarn-workspace/issues/66 but in the later ticket there's a comment that it's not complete. As soon as this piece of work is complete I can add this capability to the UI. I don't expect it will take much effort.

**Comment by Conal-Tuohy** [comment]
This issue, #70, is about a stylesheet that converts a TEI `surface` file into HTML. It shouldn't be confused with #29 and #66 which are actually quite different, if I understand them correctly:

- #29 is about a stylesheet which accepts an arbitrary TEI document, and filters out unwanted markup, yielding a simplified TEI document that conforms to a narrower, Nyingarn-specific, schema.
- #66 is about converting individual `surface` TEI files into a complete TEI file; at least that's what I took it to mean. It needs to stitch all the `surface` files together and stick a `teiHeader` on the front to make a full TEI file. This stylesheet is actually written, BTW, but it needs integration into the HTTP request-handling, and a UI.

**Comment by marcolarosa** [comment]
This [comment](https://github.com/CoEDL/nyingarn-workspace/issues/29#issuecomment-1062535945) discussed the XSLT to generate a rendering of an XML file so it is very much related to this issue and the overlap with #66 is that both tickets are discussing the surface elements. In the case of #66 once that work is completed we will also need to be able to generate a view of that data. This is why I've related these tickets.

**Comment by Conal-Tuohy** [comment]
For the task of generating HTML from TEI, I think a single stylesheet can handle the case where just a "stub" file is being presented (i.e. where the root element is a `<surface>`) and also the case where the root element is the standard TEI top-level element `<TEI>`. I have a bunch of stylesheets I've used in other projects which can be used with little modification. e.g. https://github.com/Conal-Tuohy/swinburne/blob/master/xslt/p5-to-html.xsl

The task splits into two parts: rendering the `teiHeader` metadata elements, which can be presented in an HTML table very easily, and then rendering the transcription elements `<p>`, `<div>`, `<head>`, etc. For this latter part, most TEI elements naturally fall into two classes; either they are "inline" elements that can be converted generically into an HTML `<span>` or they are "block" elements that can be converted into an HTML `<div>`, meaning they can all be converted using just a couple of XSLT templates. There are a few (such as TEI `table`, `row`, `cell`, etc) that need their own template to convert to the HTML equivalent, but again it's a totally straightforward mapping.

**Comment by marcolarosa** [comment]
I'm not clear on what I need to do.

> For the task of generating HTML from TEI, I think a single stylesheet can handle the case where just a "stub" file is being presented (i.e. where the root element is a `<surface>`) and also the case where the root element is the standard TEI top-level element `<TEI>`. I have a bunch of stylesheets I've used in other projects which can be used with little modification. e.g. https://github.com/Conal-Tuohy/swinburne/blob/master/xslt/p5-to-html.xsl

Am I supposed to use this XSLT?

**Comment by Conal-Tuohy** [comment]
I think that XSLT can be used with some modification. It contains most of what's needed. But it also contains a bunch of stuff specific to the Swinburne project which isn't needed here.

**Comment by Conal-Tuohy** [comment]
PR #99 deals with this
