### ISSUE TITLE
don't import transcriber and editor comments from digivol

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#80]
![Screenshot (266)](https://user-images.githubusercontent.com/91518014/182510762-253e39d2-0bc4-425d-843b-a7183590047f.png)
DigiVol transcriber comments and names are being ingested into the workspace.

The DigiVol csv files contains many columns including transcriber name and comments. These are not relevant to the transcription and do not need to be presented in the workspace. This issue can be seen in the workspace, manuscript example New Norcia38. The Digivol csv file has been saved to the google drive with this issue number. A screenshot of workspace is also attached. 
https://drive.google.com/drive/folders/19AHAYEJjnwH2lEV7_T3ZW-zdc2xdEvB0?usp=sharing

**Comment by marcolarosa** [comment]
[Issue - unwanted text from digivol / NewNorcia](https://drive.google.com/drive/folders/19AHAYEJjnwH2lEV7_T3ZW-zdc2xdEvB0)

**Comment by Conal-Tuohy** [comment]
fixed in 9cdb23b
