### ISSUE TITLE
Unbound namespace prefix: "xsi" at line 1 column 236

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#88]
### 1 Describe the problem

Processing Grey_g_12_c12 results in the error: `Unbound namespace prefix: "xsi" at line 1 column 236`.

Test case: 

[Issue - tei didn't upload/Grey_g_12_c_12 - github #88](https://drive.google.com/drive/folders/14HeFQMN0sobarjAqt3ilLvpMH2taoDVg?usp=sharing)

Error in the UI from processin
<img width="923" alt="Screen Shot 2022-08-23 at 3 43 26 pm" src="https://user-images.githubusercontent.com/2639995/186079228-a56a6825-2f45-40eb-b816-7af93b90eaa7.png">

**Comment by marcolarosa** [comment]
From @Conal-Tuohy  The file is not well formed so we can't parse it which means we can't fix it without writing our own parser. Which is not an option.

The code reports the error sensibly so nothing to do here.

Notes for user: open in an XML aware editor and repair it.

Error to become:
Unable to parse the file. Please try opening up in an XML aware editor (e.g. oXygen) and fix.

**Comment by Conal-Tuohy** [comment]
Handle this as part of #59 

The error thrown in this case will be https://www.w3.org/TR/xpath-functions-31/#ERRFODC0002
