### ISSUE TITLE
Transcription OCR 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#9]
Workspace 
<img width="1019" alt="Screen Shot 2022-02-16 at 1 25 46 pm" src="https://user-images.githubusercontent.com/91518014/154184894-2af47db0-4d8b-40b8-a2a2-2eb29512bda8.png">
<img width="941" alt="Screen Shot 2022-02-16 at 1 23 34 pm" src="https://user-images.githubusercontent.com/91518014/154184911-b2638f2b-c69e-484c-a89e-8db3c41d002e.png">
Examples Curr_Barlee-1 and Curr_Barlee-3, in the OCR view the manuscript listing and word association is lost when the table/column format is not replicated

**Comment by marcolarosa** [comment]
Textract supports extracting tables but it costs more per document and then we need to decide what it means anyway. Let's talk about this on Monday and then update this ticket with the outcome we decide upon.

**Comment by marcolarosa** [comment]
More on this from conversation with Amy. 

She wants to be able to copy and paste the tabular data into something else (e.g. excel) to do more with it. This makes the case for extracting tables but trying to encode meaning via heuristics just by looking at the structure will likely be difficult at best so we still need an ability for users to mark up tabular content.

**Comment by nthieberger** [comment]
In Bates we used a MS Word table for data entry that was then extracted into the tabular form presented in questionnaires in the project

**Comment by marcolarosa** [comment]
@nthieberger wants a control for a user to be able run a specific resource through textract table extraction. This needs to be joined in to the raw ocr so the user can then edit / fix from there.

**Comment by marcolarosa** [comment]
Done 317a81cb202dc20c1c2a4292e3f1a5474c8a42ca
