### ISSUE TITLE
How do we mark up strikethrough and underline in TEI

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#94]
@Conal-Tuohy @nthieberger @sophlew

@sophlew Picked up that data coming in from word via oxgarage has strikethrough as:

```
<hi rend="strikethrough"></hi>
```

However, the `S` (strikethrough button) in the workspace wraps:

```
<s></s>
```

@sophlew and I can't see that `<s>` means strikethrough in the [TEI spec.](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-group.html) so thinking this is incorrect. Is the `hi rend...` way the correct way to mark a strikethrough?

(I have a vague recollection that `s` is from a very early list of things to support though no longer sure it's correct)

Seems that underline is in the same boat.

**Comment by sophlew** [comment]
Screenshot of underline example
<img width="1271" alt="Screen Shot 2022-09-07 at 3 54 53 pm" src="https://user-images.githubusercontent.com/91518014/188799579-c000850c-3757-45ae-904f-c85840bacacc.png">

**Comment by Conal-Tuohy** [comment]
Yes it's correct to use the `hi` (highlight) element to mark up any kind of specially-formatted text. The `rend` attribute can be used to record what kind of highlighting it is, as a token like `strikethrough` or `underline`, or potentially as a sequence of such tokens separated by white space.

I had a meeting with Sophie last week where we discussed the issue of these "shortcut" elements, and where they should be allowed. Sophie's decision was that we should not use the shortcut elements in the Nyingarn workspace (so the XML there is always standard TEI), but that we should accept these shortcut elements in Digivol transcripts and transform them into `hi` elements on ingest.

**Comment by Conal-Tuohy** [comment]
NB it's also legal to use the `style` attribute instead of the `rend` attribute. The `style` attribute is for using CSS, e.g. `<hi style="text-decoration: underline">` and `<hi style="text-decoration: line-through">`. We are actually using `style` for text-alignment, because it's the markup that OxGarage produces, but maybe we should transform e.g. `style="text-align:center"` to e.g. `rend="center"`? It's more concise.

**Comment by Conal-Tuohy** [comment]
> Ok, so to double-check. The workspace will accept shortcut elements used by transcribers in DigiVol for example? If so, great. In the workspace though, tei conversion button </>, the blue markup buttons (left of transcription box) and oxgarage documents should produce the same result, hi rend .... ?

Yes I think so. The Word files via OxGarage conversion do currently produce `<hi rend="underline">` and `<hi rend="strikethrough">` (those are the only two `rend` values that make it through the conversion).
